const { onRequest } = require('firebase-functions/v2/https');
const { defineSecret } = require('firebase-functions/params');
const { getApps, initializeApp } = require('firebase-admin/app');
const { getFirestore, FieldValue } = require('firebase-admin/firestore');
const crypto = require('crypto');
const OpenAI = require('openai');
if (!getApps().length) initializeApp();
const db=getFirestore(),OPENAI_API_KEY=defineSecret('OPENAI_API_KEY'),REGION='southamerica-east1';
const ORIGINS=new Set(['https://ernandes-sobreira.github.io','http://localhost:5000','http://localhost:5500','http://127.0.0.1:5500']);
const sha=v=>crypto.createHash('sha256').update(String(v)).digest('hex');
function cors(req,res){const o=req.get('origin');if(o&&ORIGINS.has(o)){res.set('Access-Control-Allow-Origin',o);res.set('Vary','Origin')}res.set('Access-Control-Allow-Headers','Content-Type, X-Easy-Lattes-Client');res.set('Access-Control-Allow-Methods','POST, OPTIONS')}
function clean(body){const x=body&&typeof body==='object'?body:{};const xml=x.xml&&typeof x.xml==='object'?x.xml:{};const pub=x.public&&typeof x.public==='object'?x.public:{};return{researcher:String(xml.profile?.name||'').slice(0,160),institution:String(xml.profile?.institution||'').slice(0,180),counts:xml.counts||{},external_institutions:Array.isArray(xml.externalInstitutions)?xml.externalInstitutions.slice(0,20):[],foreign_countries:Array.isArray(xml.foreignCountries)?xml.foreignCountries.slice(0,20):[],recent:xml.recent||{},bibliometrics:{matched:!!pub.match,source:'OpenAlex',h_index:Number.isFinite(Number(pub.hIndex))?Number(pub.hIndex):null,i10:Number.isFinite(Number(pub.i10))?Number(pub.i10):null,citations:Number.isFinite(Number(pub.citations))?Number(pub.citations):null,works:Number.isFinite(Number(pub.worksCount))?Number(pub.worksCount):null,open_access_share:Number.isFinite(Number(pub.oaShare))?Number(pub.oaShare):null,coauthors:Number.isFinite(Number(pub.coauthors))?Number(pub.coauthors):null,institutions:Number.isFinite(Number(pub.institutions))?Number(pub.institutions):null,countries:Number.isFinite(Number(pub.countries))?Number(pub.countries):null,international_works:Number.isFinite(Number(pub.internationalWorks))?Number(pub.internationalWorks):null,top_works:Array.isArray(pub.topWorks)?pub.topWorks.slice(0,6).map(w=>({title:String(w.title||'').slice(0,260),year:w.year||null,citations:Number(w.citations||0)})):[]}}}
const dimension={type:'object',additionalProperties:false,required:['name','evidence','reading','next_step'],properties:{name:{type:'string'},evidence:{type:'string'},reading:{type:'string'},next_step:{type:'string'}}};
const schema={type:'object',additionalProperties:false,required:['headline','identity','executive_summary','dimensions','bibliometric_reading','internationalization','student_training','institutional_networks','visibility','social_reach','technical_innovation','governance_and_service','priorities','suggested_summary','caution'],properties:{headline:{type:'string'},identity:{type:'string'},executive_summary:{type:'string'},dimensions:{type:'array',minItems:6,maxItems:10,items:dimension},bibliometric_reading:{type:'string'},internationalization:{type:'string'},student_training:{type:'string'},institutional_networks:{type:'string'},visibility:{type:'string'},social_reach:{type:'string'},technical_innovation:{type:'string'},governance_and_service:{type:'string'},priorities:{type:'array',minItems:4,maxItems:7,items:{type:'string'}},suggested_summary:{type:'string'},caution:{type:'string'}}};
exports.academicAnalysisV8=onRequest({region:REGION,secrets:[OPENAI_API_KEY],timeoutSeconds:75,memory:'256MiB',maxInstances:20},async(req,res)=>{cors(req,res);if(req.method==='OPTIONS')return res.status(204).send('');if(req.method!=='POST')return res.status(405).json({error:'method_not_allowed'});if(req.get('origin')&&!ORIGINS.has(req.get('origin')))return res.status(403).json({error:'origin_not_allowed'});if(Buffer.byteLength(JSON.stringify(req.body||{}),'utf8')>120000)return res.status(413).json({error:'payload_too_large'});const payload=clean(req.body),key=sha(`academic-v8|${JSON.stringify(payload)}`);try{const snap=await db.collection('easyLattesAcademicV8Cache').doc(key).get();if(snap.exists){const d=snap.data()||{},t=d.createdAt?.toMillis?.()||0;if(t&&Date.now()-t<30*864e5)return res.json({...d.payload,meta:{...(d.payload?.meta||{}),cached:true}})}}catch(_){ }
try{const openai=new OpenAI({apiKey:OPENAI_API_KEY.value()}),model=process.env.EASY_LATTES_ACADEMIC_MODEL||'gpt-5.6-luna';const response=await openai.responses.create({model,store:false,reasoning:{effort:'medium'},max_output_tokens:3600,prompt_cache_key:'easy-lattes-academic-v8',instructions:['Você é um consultor de carreira acadêmica brasileira dentro do Easy Lattes.','Analise somente os dados fornecidos do XML Lattes e, quando presentes, as métricas OpenAlex.','Nunca transforme quantidade em qualidade, nunca invente liderança, impacto, internacionalização ou reconhecimento.','Diferencie evidência, leitura e próximo passo.','Analise explicitamente: produção científica; produção técnica e inovação; formação de pessoas; produção com discentes; bancas; comitês/serviço acadêmico; redes entre instituições; internacionalização; visibilidade; e evidências de alcance social/transferência.','Impacto social não pode ser afirmado apenas por contagem. Use a expressão evidências de alcance, transferência ou potencial de impacto quando não houver resultado social documentado.','Explique bibliometria com cautela: h-index e citações são da fonte OpenAlex e podem diferir do Google Acadêmico.','Interação com outras IES deve ser descrita por instituições detectadas, sem inferir intensidade ou qualidade da parceria.','Produção com discentes é uma estimativa por correspondência de nomes e precisa de conferência.','Dê prioridades práticas para melhorar o currículo e a estratégia profissional, nunca para inflar produção.','Escreva em português do Brasil, com parágrafos curtos, títulos claros e linguagem útil para professor/pesquisador.'].join(' '),input:JSON.stringify(payload),text:{verbosity:'medium',format:{type:'json_schema',name:'easy_lattes_academic_v8',strict:true,schema}}});const usage=response.usage||{},out={result:JSON.parse(response.output_text||'{}'),meta:{model,input_tokens:Number(usage.input_tokens||0),output_tokens:Number(usage.output_tokens||0),cached:false}};try{await db.collection('easyLattesAcademicV8Cache').doc(key).set({payload:out,createdAt:FieldValue.serverTimestamp()})}catch(_){ }return res.json(out)}catch(e){console.error('academicAnalysisV8',e);return res.status(500).json({error:'analysis_failed'})}});