(() => {
  const q=(s,r=document)=>r.querySelector(s), qa=(s,r=document)=>[...r.querySelectorAll(s)];
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
  const A={xml:null,public:null,loading:false,lastKey:'',error:''};
  const count=(doc,s)=>{try{return qa(s,doc).length}catch{return 0}};
  const allEls=doc=>qa('*',doc);
  const attr=(el,names)=>{for(const n of names){const v=el?.getAttribute?.(n);if(v)return v}return''};
  const sim=(a,b)=>{const A1=new Set(norm(a).split(' ').filter(x=>x.length>2)),B1=new Set(norm(b).split(' ').filter(x=>x.length>2));if(!A1.size||!B1.size)return 0;let n=0;A1.forEach(x=>{if(B1.has(x))n++});return 2*n/(A1.size+B1.size)};
  function toast(msg){const s=q('#toastStack');if(!s)return;const d=document.createElement('div');d.className='toast';d.textContent=msg;s.appendChild(d);setTimeout(()=>d.remove(),3300)}

  function profile(doc){const dg=doc?.querySelector('DADOS-GERAIS');const name=dg?.getAttribute('NOME-COMPLETO')||'';let orcid=dg?.getAttribute('ORCID-ID')||'';if(!orcid){for(const el of allEls(doc)){orcid=el.getAttribute?.('ORCID-ID')||el.getAttribute?.('ORCID')||'';if(orcid)break}}orcid=orcid.replace(/^https?:\/\/orcid.org\//,'');let institution='';for(const el of allEls(doc)){for(const n of ['NOME-INSTITUICAO','NOME-INSTITUICAO-EMPRESA','NOME-DA-INSTITUICAO']){const v=el.getAttribute?.(n);if(v){institution=v;break}}if(institution)break}return{name,orcid,institution}}
  function natureCount(doc,nature){return qa('TRABALHO-EM-EVENTOS',doc).filter(el=>el.querySelector('DADOS-BASICOS-DO-TRABALHO')?.getAttribute('NATUREZA')===nature).length}
  function tagLike(doc,regex){return allEls(doc).filter(el=>regex.test(el.tagName)&&!/^(DADOS|DETALHAMENTO|INFORMACOES|AREAS|PALAVRAS|SETORES|AUTORES)/.test(el.tagName)).length}
  function uniqueAttrValues(doc,regex){const out=[];for(const el of allEls(doc))for(const a of [...(el.attributes||[])])if(regex.test(a.name)&&String(a.value||'').trim())out.push(a.value.trim());return [...new Set(out)]}
  function advisees(doc){const out=[];for(const el of allEls(doc))for(const a of [...(el.attributes||[])])if(/NOME-DO-ORIENTAND|NOME-DO-ORIENTAD|NOME-DO-ALUNO/i.test(a.name)&&a.value)out.push(a.value);return [...new Set(out.map(norm))].filter(x=>x.length>6)}
  function authorsOf(el){const out=[];qa('AUTORES',el).forEach(a=>{const v=a.getAttribute('NOME-COMPLETO-DO-AUTOR')||a.getAttribute('NOME-PARA-CITACAO')||'';if(v)out.push(norm(v))});return out}
  function productionWithStudents(doc){const students=advisees(doc);if(!students.length)return{count:0,students:0};let n=0;for(const el of qa('[SEQUENCIA-PRODUCAO]',doc)){const authors=authorsOf(el);if(authors.some(a=>students.some(s=>sim(a,s)>.83))){n++}}return{count:n,students:students.length}}
  function institutions(doc,own){const vals=uniqueAttrValues(doc,/INSTITUICAO|INSTITUIÇÃO/i).filter(x=>x.length>3);const external=vals.filter(x=>!own||sim(x,own)<.72);return{all:vals,external:[...new Set(external)]}}
  function foreignCountries(doc){const vals=uniqueAttrValues(doc,/PAIS|PAÍS/i).filter(x=>x.length>1);const foreign=vals.filter(x=>!/^(brasil|brazil|br)$/i.test(norm(x)));return [...new Set(foreign)]}
  function yearsRecent(doc){const now=new Date().getFullYear(),m={};for(let y=now-4;y<=now;y++)m[y]=0;qa('[SEQUENCIA-PRODUCAO]',doc).forEach(el=>{for(const node of [el,...qa('*',el)])for(const a of [...(node.attributes||[])])if(/(^ANO$|ANO-|ANO-DO|ANO-DA)/i.test(a.name)&&m[a.value]!==undefined){m[a.value]++;return}});return m}
  function xmlSnapshot(doc){const p=profile(doc),student=productionWithStudents(doc),inst=institutions(doc,p.institution),foreign=foreignCountries(doc);const c={
    artigos:count(doc,'ARTIGO-PUBLICADO'),artigosAceitos:count(doc,'ARTIGO-ACEITO-PARA-PUBLICACAO'),livros:count(doc,'LIVRO-PUBLICADO-OU-ORGANIZADO'),capitulos:count(doc,'CAPITULO-DE-LIVRO-PUBLICADO'),
    eventosCompleto:natureCount(doc,'COMPLETO'),eventosResumo:natureCount(doc,'RESUMO'),eventosResumoExpandido:natureCount(doc,'RESUMO_EXPANDIDO'),
    software:count(doc,'PRODUCAO-TECNICA > SOFTWARE'),produtoTecnologico:count(doc,'PRODUCAO-TECNICA > PRODUTO-TECNOLOGICO'),patentes:count(doc,'PATENTE'),processos:count(doc,'PROCESSOS-OU-TECNICAS'),trabalhosTecnicos:count(doc,'TRABALHO-TECNICO'),materialDidatico:count(doc,'DESENVOLVIMENTO-DE-MATERIAL-DIDATICO-OU-INSTRUCIONAL'),relatorios:count(doc,'RELATORIO-DE-PESQUISA'),sites:count(doc,'MIDIA-SOCIAL-WEBSITE-BLOG'),cursosMinistrados:count(doc,'CURSO-DE-CURTA-DURACAO-MINISTRADO'),
    apresentacoes:count(doc,'APRESENTACAO-DE-TRABALHO'),eventos:count(doc,'PARTICIPACAO-EM-EVENTOS-CONGRESSOS [SEQUENCIA-PRODUCAO]'),bancas:count(doc,'PARTICIPACAO-EM-BANCA-TRABALHOS-CONCLUSAO [SEQUENCIA-PRODUCAO],PARTICIPACAO-EM-BANCA-JULGADORA [SEQUENCIA-PRODUCAO]'),
    orientacoesConcluidas:tagLike(doc,/ORIENTACOES-CONCLUIDAS|ORIENTACAO-CONCLUIDA|OUTRAS-ORIENTACOES-CONCLUIDAS/i),orientacoesAndamento:tagLike(doc,/ORIENTACAO-EM-ANDAMENTO|ORIENTACOES-EM-ANDAMENTO/i),projetos:count(doc,'PROJETO-DE-PESQUISA'),premios:count(doc,'PREMIO-TITULO'),comites:tagLike(doc,/CONSELHO|COMISSAO|COMITE|COMITÊ/i),
    producaoComDiscentes:student.count,discentesIdentificados:student.students,iesExternas:inst.external.length,paisesEstrangeiros:foreign.length
  };
  c.bibliografica=c.artigos+c.artigosAceitos+c.livros+c.capitulos+c.eventosCompleto+c.eventosResumo+c.eventosResumoExpandido;
  c.tecnica=c.software+c.produtoTecnologico+c.patentes+c.processos+c.trabalhosTecnicos+c.materialDidatico+c.relatorios+c.sites+c.cursosMinistrados;
  c.transferencia=c.produtoTecnologico+c.software+c.processos+c.materialDidatico+c.relatorios+c.sites+c.cursosMinistrados+c.trabalhosTecnicos;
  return{profile:p,counts:c,externalInstitutions:inst.external.slice(0,20),foreignCountries:foreign.slice(0,20),recent:yearsRecent(doc)}
  }

  async function getAuthorCandidates(p){if(p.orcid){const r=await fetch(`https://api.openalex.org/authors?filter=orcid:${encodeURIComponent(p.orcid)}&per-page=5`);if(r.ok){const j=await r.json();if(j.results?.length)return j.results}}const r=await fetch(`https://api.openalex.org/authors?search=${encodeURIComponent(p.name)}&per-page=8`);if(!r.ok)throw new Error('OpenAlex authors');return (await r.json()).results||[]}
  function authorScore(a,p){let s=sim(a.display_name||'',p.name)*.75;const insts=(a.last_known_institutions||[]).map(x=>x.display_name||'');if(p.institution&&insts.length)s+=Math.max(...insts.map(x=>sim(x,p.institution)))*.2;if(p.orcid&&String(a.orcid||'').includes(p.orcid))s+=.25;return s}
  async function openAlexSnapshot(p){if(!p.name)return null;const candidates=await getAuthorCandidates(p);const scored=candidates.map(a=>({a,score:authorScore(a,p)})).sort((x,y)=>y.score-x.score);const best=scored[0];if(!best||best.score<.55)return{match:false,candidates:scored.slice(0,3).map(x=>({name:x.a.display_name,score:Math.round(x.score*100)}))};const a=best.a,id=String(a.id||'').split('/').pop();let works=[];try{const url=`https://api.openalex.org/works?filter=author.id:${encodeURIComponent(id)}&per-page=100&sort=cited_by_count:desc`;const r=await fetch(url);if(r.ok)works=(await r.json()).results||[]}catch(_){ }
    const countries=new Set(),institutions=new Set(),coauthors=new Set();let oa=0,internationalWorks=0;
    for(const w of works){let foreign=false;if(w.open_access?.is_oa)oa++;for(const au of w.authorships||[]){if(au.author?.id&&String(au.author.id)!==String(a.id))coauthors.add(au.author.id);for(const ins of au.institutions||[]){if(ins.display_name)institutions.add(ins.display_name);if(ins.country_code){countries.add(ins.country_code);if(ins.country_code!=='BR')foreign=true}}}if(foreign)internationalWorks++}
    return{match:true,score:Math.round(best.score*100),id:a.id,name:a.display_name||p.name,institution:(a.last_known_institutions||[])[0]?.display_name||'',worksCount:a.works_count||works.length,citations:a.cited_by_count||0,hIndex:a.summary_stats?.h_index??null,i10:a.summary_stats?.i10_index??null,twoYr:a.summary_stats?.['2yr_mean_citedness']??null,oaShare:works.length?Math.round(oa/works.length*100):null,coauthors:coauthors.size,institutions:institutions.size,countries:countries.size,internationalWorks,topWorks:works.slice(0,6).map(w=>({title:w.display_name||w.title||'',year:w.publication_year||'',citations:w.cited_by_count||0,doi:w.doi||''}))}
  }
  function cacheKey(p){return `easyLattesOpenAlexV8:${norm(p.name)}:${norm(p.institution)}:${p.orcid||''}`}
  async function loadPublic(force=false){if(!A.xml)return;const p=A.xml.profile,key=cacheKey(p);if(!force){try{const c=JSON.parse(localStorage.getItem(key)||'null');if(c&&Date.now()-c.time<24*3600e3){A.public=c.data;A.lastKey=key;return}}catch(_){}}A.loading=true;A.error='';render();try{A.public=await openAlexSnapshot(p);A.lastKey=key;localStorage.setItem(key,JSON.stringify({time:Date.now(),data:A.public}))}catch(e){A.error=e.message||'OpenAlex indisponível';A.public=null}finally{A.loading=false;render()}}

  const metric=(label,value,desc,neon=false)=>`<article class="acad-metric ${neon?'neon':''}"><span>${esc(label)}</span><strong>${value==null?'—':esc(value)}</strong><p>${esc(desc)}</p></article>`;
  const tile=(icon,n,title,desc)=>`<article class="acad-tile"><div class="icon"><i data-lucide="${icon}"></i></div><strong>${esc(n)}</strong><h5>${esc(title)}</h5><p>${esc(desc)}</p></article>`;
  const row=(title,n,sub='')=>`<div class="acad-list-row"><div><strong>${esc(title)}</strong>${sub?`<span>${esc(sub)}</span>`:''}</div><strong>${esc(n)}</strong></div>`;
  function render(){const career=q('#careerContent');if(!career||!A.xml)return;let root=q('#academicV8');if(!root){root=document.createElement('div');root.id='academicV8';root.className='academic-v8';career.prepend(root)}const x=A.xml,c=x.counts,p=A.public;
    const pubHtml=A.loading?`<div class="acad-loading"><div class="acad-spinner"></div><div><strong>Atualizando bibliometria pública…</strong><p>Confirmando identidade no OpenAlex e lendo citações, colaboração e acesso aberto.</p></div></div>`:p?.match?`<div class="acad-biblio">${metric('Índice h',p.hIndex,'OpenAlex • pode diferir do Google Acadêmico',true)}${metric('Citações',p.citations,'citações registradas no OpenAlex')}${metric('i10',p.i10,'trabalhos com pelo menos 10 citações')}${metric('Trabalhos',p.worksCount,'obras associadas ao perfil público')}${metric('Acesso aberto',p.oaShare==null?'—':`${p.oaShare}%`,'entre os trabalhos consultados')}</div>`:p&&!p.match?`<div class="acad-google-note"><strong>Perfil público ainda não confirmado.</strong> Encontrei nomes semelhantes, mas não vou atribuir métricas sem segurança. Nome, instituição e ORCID ajudam a resolver homônimos.</div>`:`<div class="acad-google-note"><strong>Bibliometria pública ainda não carregada.</strong> Clique em “Atualizar métricas públicas”.</div>`;
    root.innerHTML=`
      <section class="acad-hero"><div class="acad-kicker">PANORAMA ACADÊMICO COMPLETO</div><h3>Produção, formação, redes, internacionalização e impacto — cada coisa no seu lugar.</h3><p>O Easy Lattes separa o que vem do XML do que vem de bases públicas. Quantidade não é tratada como qualidade e “impacto social” só aparece como evidência registrada, nunca como conclusão automática.</p><div class="acad-hero-actions"><button class="btn neon" id="acadRefresh"><i data-lucide="refresh-cw"></i>Atualizar métricas públicas</button><button class="btn ghost" data-go="discovery"><i data-lucide="search-check"></i>Procurar atividades esquecidas</button></div><div class="acad-source-note">Currículo: <strong>Lattes importado</strong> • Bibliometria: <strong>OpenAlex</strong>${p?.match?` • identidade pública ${p.score}% compatível`:''}</div></section>
      <section class="acad-section"><div class="acad-section-head"><div><h4>Bibliometria pública</h4><p>Uma leitura parecida com o que você procura no Google Acadêmico, mas baseada em uma fonte com API própria e rastreável.</p></div><small>fonte externa</small></div>${pubHtml}<div class="acad-google-note" style="margin-top:14px"><strong>Google Acadêmico:</strong> os números podem ser diferentes porque as bases indexam conjuntos distintos. Para um produto comercial, o Easy Lattes não deve raspar o Google Scholar automaticamente; a API de pesquisa do Google disponível a pesquisadores tem finalidade não comercial. Podemos depois permitir importar uma captura/perfil como dado informado pelo próprio usuário.</div></section>
      <section class="acad-section"><div class="acad-section-head"><div><h4>Produção bibliográfica — sem misturar tudo</h4><p>Artigos, livros e trabalhos em eventos aparecem separados. Resumo simples e resumo expandido deixam de ficar escondidos.</p></div><small>XML Lattes</small></div><div class="acad-breakdown"><div class="acad-list">${row('Artigos publicados',c.artigos)}${row('Artigos aceitos',c.artigosAceitos)}${row('Livros',c.livros)}${row('Capítulos de livro',c.capitulos)}${row('Trabalhos completos em eventos',c.eventosCompleto)}${row('Resumos expandidos',c.eventosResumoExpandido)}${row('Resumos em eventos',c.eventosResumo)}</div><div class="acad-readout"><div class="read-kicker">LEITURA</div><h5>${c.bibliografica} registros bibliográficos identificados.</h5><p>O número sozinho não diz qualidade. A análise profunda usa tipo de produção, recência, temas e bibliometria pública para construir uma leitura mais útil.</p><p>Se um artigo encontrado no Crossref ainda não estiver no XML, a Caixa Acadêmica agora deve tratá-lo como <strong>artigo</strong>, não como “outra produção técnica”.</p><div class="warn">Os indicadores bibliométricos externos não alteram o XML; servem para análise e conferência.</div></div></div></section>
      <section class="acad-section"><div class="acad-section-head"><div><h4>Produtos intelectuais e produção técnica</h4><p>Software, produtos, processos e materiais passam a aparecer como categorias próprias.</p></div><small>XML Lattes</small></div><div class="acad-grid">${tile('code-2',c.software,'Software','programas e sistemas registrados')}${tile('lightbulb',c.produtoTecnologico,'Produtos tecnológicos','protótipos, pilotos, produtos e similares')}${tile('badge-check',c.patentes,'Patentes / registros','registros encontrados no currículo')}${tile('workflow',c.processos,'Processos ou técnicas','processos/técnicas registrados')}${tile('book-open-check',c.materialDidatico,'Material didático','materiais instrucionais registrados')}${tile('file-chart-column',c.relatorios,'Relatórios de pesquisa','relatórios cadastrados')}${tile('briefcase-business',c.trabalhosTecnicos,'Trabalhos técnicos','consultoria, parecer, extensão etc.')}${tile('globe-2',c.sites,'Sites / mídia','website, blog e mídia social')}</div></section>
      <section class="acad-section"><div class="acad-section-head"><div><h4>Formação de pessoas e vida acadêmica</h4><p>Orientações, bancas, comitês e produção compartilhada com discentes não podem ficar escondidos em um único total.</p></div><small>XML Lattes</small></div><div class="acad-grid wide">${tile('graduation-cap',c.orientacoesConcluidas,'Orientações concluídas','registros de orientação finalizada')}${tile('hourglass',c.orientacoesAndamento,'Orientações em andamento','orientações atualmente registradas')}${tile('users-round',c.bancas,'Bancas','participações em bancas e julgamentos')}${tile('landmark',c.comites,'Conselhos / comissões / comitês','participações institucionais detectadas')}${tile('user-round-check',c.producaoComDiscentes,'Produção com discentes','produções em que um autor coincide com nomes de orientandos identificados')}${tile('presentation',c.apresentacoes,'Apresentações','palestras e apresentações registradas')}</div></section>
      <section class="acad-section"><div class="acad-section-head"><div><h4>Redes, internacionalização e circulação</h4><p>Aqui a plataforma começa a olhar para conexões acadêmicas, não apenas para quantidade de itens.</p></div><small>XML + OpenAlex</small></div><div class="acad-collab">${`<article class="acad-signal highlight"><strong>${p?.match?p.coauthors:'—'}</strong><span>Coautores públicos</span><p>coautores distintos nos trabalhos consultados no OpenAlex</p></article>`}${`<article class="acad-signal"><strong>${p?.match?p.institutions:c.iesExternas}</strong><span>Instituições conectadas</span><p>${p?.match?'instituições identificadas nas coautorias públicas':'IES/instituições externas mencionadas no XML'}</p></article>`}${`<article class="acad-signal"><strong>${p?.match?p.countries:c.paisesEstrangeiros}</strong><span>Países nas redes</span><p>${p?.match?'países identificados nas afiliações de coautores':'países estrangeiros mencionados no XML'}</p></article>`}${`<article class="acad-signal"><strong>${p?.match?p.internationalWorks:'—'}</strong><span>Trabalhos com rede internacional</span><p>trabalhos consultados com ao menos uma instituição fora do Brasil</p></article>`}</div></section>
      <section class="acad-section"><div class="acad-section-head"><div><h4>Alcance social e transferência</h4><p>Não chamo isso automaticamente de “impacto social”. Mostro evidências registradas que podem sustentar uma análise de impacto.</p></div><small>proxy descritivo</small></div><div class="acad-grid two">${tile('heart-handshake',c.transferencia,'Evidências de transferência / alcance','software + produtos + processos + materiais + relatórios + cursos + trabalhos técnicos')}${tile('school',c.cursosMinistrados,'Cursos / minicursos ministrados','ações formativas registradas no currículo')}${tile('network',c.iesExternas,'Interações institucionais','instituições diferentes da principal identificadas no XML')}${tile('flask-conical',c.projetos,'Projetos','projetos de pesquisa registrados')}</div></section>
      ${p?.match&&p.topWorks?.length?`<section class="acad-section"><div class="acad-section-head"><div><h4>Trabalhos mais citados no OpenAlex</h4><p>Útil para enxergar quais temas estão circulando mais. Citação não é sinônimo de qualidade ou impacto social.</p></div><small>fonte externa</small></div><div class="acad-topworks">${p.topWorks.map((w,i)=>`<article class="acad-work"><div class="rank">${i+1}</div><div><strong>${esc(w.title)}</strong><p>${esc(w.year||'ano não informado')}</p></div><div class="cites">${w.citations} citações</div></article>`).join('')}</div></section>`:''}
      <section class="acad-section"><div class="acad-section-head"><div><h4>Como ler estes indicadores</h4><p>O objetivo é orientar decisões sem transformar o pesquisador em uma nota.</p></div></div><div class="acad-explain"><article><strong>Índice h</strong><p>Combina volume e citações: h trabalhos precisam ter pelo menos h citações cada. Aqui a fonte é OpenAlex.</p></article><article><strong>Internacionalização</strong><p>É descrita por países e instituições nas redes de coautoria e pelos registros internacionais do XML; não é uma nota de mérito.</p></article><article><strong>Impacto social</strong><p>Produtos, cursos, materiais e extensão são evidências de transferência. Impacto real exige contexto, público alcançado e resultados documentados.</p></article><article><strong>Produção com discentes</strong><p>É estimada cruzando nomes de orientandos com autores das produções. Precisa de conferência quando houver homônimos ou variações de nome.</p></article><article><strong>Interação com outras IES</strong><p>Conta instituições externas detectadas no currículo e, quando disponível, nas afiliações públicas de coautores.</p></article><article><strong>Comitês e bancas</strong><p>São dimensões próprias da atuação acadêmica e passam a aparecer separadamente da produção bibliográfica.</p></article></div></section>`;
    q('#acadRefresh')?.addEventListener('click',()=>loadPublic(true));window.lucide?.createIcons?.();
    window.__easyLattesAcademicV8={xml:A.xml,public:A.public,generatedAt:new Date().toISOString()};
  }
  function refresh(){const doc=window.__easyLattesCurrentDoc;if(!doc)return;A.xml=xmlSnapshot(doc);render();loadPublic(false)}
  function ensureWhenCareer(){if(q('#view-career')?.classList.contains('active')&&window.__easyLattesCurrentDoc){if(!A.xml)refresh();else render()}}
  function init(){window.addEventListener('easy-lattes:xml-ready',()=>setTimeout(refresh,100));window.addEventListener('easy-lattes:xml-mutated',()=>setTimeout(()=>{A.xml=xmlSnapshot(window.__easyLattesCurrentDoc);render()},80));q('[data-view="career"]')?.addEventListener('click',()=>setTimeout(ensureWhenCareer,140));const box=q('#careerContent');if(box){new MutationObserver(()=>{if(q('#view-career')?.classList.contains('active')&&A.xml&&!q('#academicV8'))setTimeout(render,20)}).observe(box,{childList:true})}if(window.__easyLattesCurrentDoc){A.xml=xmlSnapshot(window.__easyLattesCurrentDoc);ensureWhenCareer()}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,260));else setTimeout(init,260);
})();