const S={xmlName:null,xmlText:null,doc:null,researcher:null,items:[],issues:[],files:[],changes:[],score:null,cursor:0,demo:false};
const $=id=>document.getElementById(id), $$=q=>[...document.querySelectorAll(q)];
const LABEL={artigo:'Artigo',livro:'Livro',capitulo:'Capítulo',orientacao:'Orientação',banca:'Banca',evento:'Evento',projeto:'Projeto',tecnica:'Produção técnica'};
const ICON={artigo:'newspaper',livro:'book-open',capitulo:'book-copy',orientacao:'graduation-cap',banca:'users',evento:'calendar-days',projeto:'flask-conical',tecnica:'wrench'};
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const norm=s=>String(s??'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
const attr=(e,n)=>e?.getAttribute?.(n)||'';
const short=(s,n=90)=>String(s||'').length>n?String(s).slice(0,n-1)+'…':String(s||'');
const initials=n=>String(n||'?').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase();
const sev=s=>s==='high'?'Crítico':s==='medium'?'Atenção':'Sugestão';
const uid=()=>crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`;
function toast(m){const d=document.createElement('div');d.className='toast';d.textContent=m;$('toastStack').appendChild(d);setTimeout(()=>d.remove(),3000)}
function view(name){$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));const t={dashboard:'Seu currículo, sob controle.',lattes:'Seu Lattes, decodificado.',inbox:'Sua caixa acadêmica.',audit:'Revisão assistida.',report:'Seu XML corrigido.'};$('pageTitle').textContent=t[name]||'Easy Lattes';if(name==='audit')ensureCursor();scrollTo({top:0,behavior:'smooth'});render()}
function ref(el,attribute){return el&&el.hasAttribute(attribute)?{el,attribute}:el?{el,attribute}:null}
function findRef(root,names){for(const el of [root,...root.querySelectorAll('*')])for(const n of names)if(el.hasAttribute(n))return{el,attribute:n};return null}
function readRef(r){return r?.el?.getAttribute(r.attribute)||''}
function setRef(r,value){if(!r?.el)return false;r.el.setAttribute(r.attribute,String(value||'').trim());return true}
function item(type,source,refs,id){const data={title:readRef(refs.title),year:readRef(refs.year),doi:readRef(refs.doi),venue:readRef(refs.venue),extra:readRef(refs.extra)};const checks=[!!data.title,!!data.year,!!data.venue,type==='artigo'?!!(data.doi||data.extra):true];return{id,type,source,refs,...data,title:data.title||'(sem título identificado)',complete:Math.round(checks.filter(Boolean).length/checks.length*100),removed:false}}
function recalcItem(p){p.title=readRef(p.refs.title)||p.title||'(sem título identificado)';p.year=readRef(p.refs.year);p.doi=readRef(p.refs.doi);p.venue=readRef(p.refs.venue);p.extra=readRef(p.refs.extra);const checks=[!!p.title&&!p.title.startsWith('(sem'),!!p.year,!!p.venue,p.type==='artigo'?!!(p.doi||p.extra):true];p.complete=Math.round(checks.filter(Boolean).length/checks.length*100)}
function collect(doc,selector,type,refMap){[...doc.querySelectorAll(selector)].forEach((e,i)=>{const refs=refMap(e);S.items.push(item(type,e,refs,`${selector}-${i}-${S.items.length}`))})}
function genericRefs(e){return{title:findRef(e,['TITULO','TITULO-DO-TRABALHO','TITULO-DA-ORIENTACAO','NOME-DO-EVENTO','TITULO-DO-TRABALHO-TECNICO','TITULO-DO-CURSO-DE-CURTA-DURACAO']),year:findRef(e,['ANO','ANO-DA-ORIENTACAO','ANO-DO-TRABALHO','ANO-DO-EVENTO']),venue:findRef(e,['NOME-DA-INSTITUICAO','NOME-INSTITUICAO','NOME-DA-ENTIDADE','NOME-DO-EVENTO','NOME-DO-CURSO']),doi:null,extra:null}}
function parseXml(text,name='curriculo.xml'){
 const doc=new DOMParser().parseFromString(text,'application/xml');if(doc.querySelector('parsererror'))throw Error('XML inválido');S.xmlName=name;S.xmlText=text;S.doc=doc;S.demo=false;S.changes=[];S.cursor=0;
 const root=doc.querySelector('CURRICULO-VITAE')||doc.documentElement,d=doc.querySelector('DADOS-GERAIS');S.researcher={name:attr(d,'NOME-COMPLETO')||'Pesquisador',id:attr(root,'NUMERO-IDENTIFICADOR'),updated:attr(root,'DATA-ATUALIZACAO')};S.items=[];
 collect(doc,'ARTIGO-PUBLICADO','artigo',e=>{const b=e.querySelector('DADOS-BASICOS-DO-ARTIGO'),q=e.querySelector('DETALHAMENTO-DO-ARTIGO');return{title:ref(b,'TITULO-DO-ARTIGO'),year:ref(b,'ANO-DO-ARTIGO'),doi:ref(b,'DOI'),venue:ref(q,'TITULO-DO-PERIODICO-OU-REVISTA'),extra:ref(q,'ISSN')}});
 collect(doc,'LIVRO-PUBLICADO-OU-ORGANIZADO','livro',e=>{const b=e.querySelector('DADOS-BASICOS-DO-LIVRO'),q=e.querySelector('DETALHAMENTO-DO-LIVRO');return{title:ref(b,'TITULO-DO-LIVRO'),year:ref(b,'ANO'),doi:ref(b,'DOI'),venue:ref(q,'NOME-DA-EDITORA'),extra:ref(q,'ISBN')}});
 collect(doc,'CAPITULO-DE-LIVRO-PUBLICADO','capitulo',e=>{const b=e.querySelector('DADOS-BASICOS-DO-CAPITULO'),q=e.querySelector('DETALHAMENTO-DO-CAPITULO');return{title:ref(b,'TITULO-DO-CAPITULO-DO-LIVRO'),year:ref(b,'ANO'),doi:ref(b,'DOI'),venue:ref(q,'TITULO-DO-LIVRO'),extra:ref(q,'ISBN')}});
 const groups={orientacao:['ORIENTACOES-CONCLUIDAS-PARA-MESTRADO','ORIENTACOES-CONCLUIDAS-PARA-DOUTORADO','OUTRAS-ORIENTACOES-CONCLUIDAS'],banca:['PARTICIPACAO-EM-BANCA-DE-MESTRADO','PARTICIPACAO-EM-BANCA-DE-DOUTORADO','PARTICIPACAO-EM-BANCA-DE-TRABALHOS-DE-CONCLUSAO'],evento:['PARTICIPACAO-EM-CONGRESSO','PARTICIPACAO-EM-SEMINARIO','PARTICIPACAO-EM-SIMPOSIO','PARTICIPACAO-EM-ENCONTRO'],tecnica:['TRABALHO-TECNICO','CURSO-DE-CURTA-DURACAO-MINISTRADO','ORGANIZACAO-DE-EVENTO']};Object.entries(groups).forEach(([t,ss])=>ss.forEach(s=>collect(doc,s,t,genericRefs)));
 collect(doc,'PROJETO-DE-PESQUISA','projeto',e=>({title:ref(e,'NOME-DO-PROJETO'),year:ref(e,'ANO-INICIO'),venue:ref(e,'DESCRICAO-DO-PROJETO'),doi:null,extra:null}));
 audit(true);render();
}
function issueBase(kind,severity,item,data={}){return{id:uid(),kind,severity,item,status:'open',createdAt:Date.now(),...data}}
function audit(reset=false){
 const old=new Map(reset?[]:S.issues?.map(x=>[x.signature,x]));const out=[],active=S.items.filter(x=>!x.removed);const seen=new Map();
 for(const p of active){recalcItem(p);const kTitle=norm(p.title),doi=norm(p.doi);const dupKey=doi&&p.type==='artigo'?`doi|${doi}`:(kTitle.length>14&&p.year?`${p.type}|${kTitle}|${p.year}`:null);if(dupKey){if(seen.has(dupKey)){const peer=seen.get(dupKey),remove=p.complete>peer.complete?peer:p,keep=remove===p?peer:p;const confidence=doi?99:90;const sig=`dup|${keep.id}|${remove.id}`;const i=issueBase('duplicate','high',remove,{peer,keep,confidence,signature:sig,title:'Possível duplicidade',description:doi?'Mesmo DOI encontrado em dois registros.':'Mesmo tipo, título e ano encontrados em dois registros.'});out.push(Object.assign(i,old.get(sig)||{}) )}else seen.set(dupKey,p)}
 const missing=[];if(!p.year)missing.push('year');if(!p.venue)missing.push('venue');if(p.type==='artigo'&&!p.doi)missing.push('doi');if(missing.length){const severity=missing.length>=2?'high':'medium',sig=`enrich|${p.id}|${missing.join(',')}`,i=issueBase('enrich',severity,p,{missing,signature:sig,title:missing.length>1?'Cadastro incompleto':missing[0]==='doi'?'Artigo sem DOI':missing[0]==='year'?'Ano ausente':'Informação ausente',description:`${short(p.title)} precisa de ${missing.map(x=>({doi:'DOI',year:'ano',venue:'periódico/instituição'}[x])).join(', ')}.`});out.push(Object.assign(i,old.get(sig)||{}))}
 }
 S.issues=out;recalcScore();ensureCursor();return out;
}
function recalcScore(){const active=S.items.filter(x=>!x.removed);const avg=active.length?active.reduce((a,p)=>a+p.complete,0)/active.length:0;const open=S.issues.filter(x=>x.status==='open'),pen=Math.min(22,open.filter(x=>x.severity==='high').length*1.8+open.filter(x=>x.severity==='medium').length*.7);S.score=active.length?Math.max(0,Math.round(avg-pen)):null}
function ensureCursor(){const open=openIssues();if(!open.length){S.cursor=0;return}S.cursor=Math.max(0,Math.min(S.cursor,open.length-1))}
const openIssues=()=>S.issues.filter(x=>x.status==='open');
function addChange(kind,title,detail){S.changes.unshift({id:uid(),kind,title,detail,time:new Date()})}
function resolveIssue(issue,status='resolved'){issue.status=status;recalcScore();ensureCursor();render()}
function closeRelated(item){S.issues.forEach(i=>{if(i.status==='open'&&(i.item===item||i.peer===item||i.keep===item))i.status='resolved'})}
function applyDuplicate(issue){const remove=issue.item;if(!remove?.source?.parentNode)return toast('Não consegui localizar esse registro no XML.');remove.source.parentNode.removeChild(remove.source);remove.removed=true;closeRelated(remove);addChange('duplicate','Duplicidade removida',`${LABEL[remove.type]}: ${short(remove.title,120)}`);audit(false);toast('Duplicidade removida da cópia do XML.');render()}
function keepBoth(issue){issue.status='ignored';addChange('decision','Dois registros mantidos',`${LABEL[issue.item.type]}: ${short(issue.item.title,120)}`);recalcScore();ensureCursor();render();toast('Os dois registros serão mantidos.')}
function swapDuplicate(issue){const oldRemove=issue.item;issue.item=issue.keep;issue.keep=oldRemove;issue.peer=oldRemove;renderReview()}
function inputVal(id){return $(id)?.value?.trim()||''}
function applyEnrich(issue){const p=issue.item,fields={doi:inputVal('fix-doi'),year:inputVal('fix-year'),venue:inputVal('fix-venue')},changed=[];for(const [k,v] of Object.entries(fields)){if(v&&v!==p[k]&&p.refs[k]&&setRef(p.refs[k],v)){changed.push(`${k.toUpperCase()}: ${p[k]||'—'} → ${v}`);p[k]=v}}if(!changed.length){toast('Nenhuma alteração nova para aplicar.');return}recalcItem(p);issue.status='resolved';addChange('enrich','Cadastro enriquecido',`${short(p.title,110)} • ${changed.join(' • ')}`);audit(false);toast('Correção aplicada à cópia do XML.');render()}
async function lookupCrossref(issue){const p=issue.item;if(!p?.title||p.title.startsWith('(sem'))return toast('Falta um título para buscar metadados.');const btn=$('crossrefBtn');if(btn){btn.disabled=true;btn.innerHTML='<i data-lucide="loader-circle"></i>Buscando…';lucide.createIcons()}
 try{const url=`https://api.crossref.org/works?rows=5&query.title=${encodeURIComponent(p.title)}`;const r=await fetch(url,{headers:{Accept:'application/json'}});if(!r.ok)throw Error('crossref');const data=await r.json(),cand=(data?.message?.items||[]).map(x=>({x,sim:titleSimilarity(p.title,(x.title||[])[0]||'')})).sort((a,b)=>b.sim-a.sim)[0];if(!cand||cand.sim<.58)throw Error('nomatch');const x=cand.x,year=x?.published?.['date-parts']?.[0]?.[0]||x?.issued?.['date-parts']?.[0]?.[0]||'',venue=(x['container-title']||[])[0]||'',doi=x.DOI||'';issue.suggestion={doi,year:String(year||''),venue,confidence:Math.round(cand.sim*100),source:'Crossref'};renderReview();toast(`Metadados encontrados (${issue.suggestion.confidence}% de similaridade).`)}catch(e){console.error(e);toast('Não encontrei uma correspondência segura no Crossref.')}finally{const b=$('crossrefBtn');if(b)b.disabled=false}}
function titleSimilarity(a,b){const A=new Set(norm(a).split(' ').filter(x=>x.length>2)),B=new Set(norm(b).split(' ').filter(x=>x.length>2));if(!A.size||!B.size)return 0;const inter=[...A].filter(x=>B.has(x)).length;return (2*inter)/(A.size+B.size)}
function applySuggestion(issue){if(!issue.suggestion)return;['doi','year','venue'].forEach(k=>{const el=$(`fix-${k}`);if(el&&issue.suggestion[k]&&!el.value)el.value=issue.suggestion[k]});renderSuggestionHints(issue)}
function renderSuggestionHints(issue){if(!issue.suggestion)return;['doi','year','venue'].forEach(k=>{const el=$(`fix-${k}`);if(el&&issue.suggestion[k]){el.closest('.field-card')?.classList.add('suggested');const h=el.closest('.field-card')?.querySelector('.field-hint');if(h)h.textContent=`Sugestão ${issue.suggestion.source}: ${issue.suggestion[k]}`}})}
function applySafeFixes(){const safe=S.issues.filter(i=>i.status==='open'&&i.kind==='duplicate'&&i.confidence>=99);if(!safe.length)return toast('Nenhuma correção automática de alta confiança disponível agora.');safe.forEach(i=>{const remove=i.item;if(remove?.source?.parentNode){remove.source.parentNode.removeChild(remove.source);remove.removed=true;i.status='resolved';addChange('duplicate','Duplicidade exata removida',`${LABEL[remove.type]}: ${short(remove.title,120)}`)}});audit(false);toast(`${safe.length} correção(ões) segura(s) aplicada(s).`);render()}
async function loadXml(f){try{const b=await f.arrayBuffer();let t=new TextDecoder().decode(b);if(/8859-1|windows-1252/i.test(t.slice(0,180)))t=new TextDecoder('windows-1252').decode(b);parseXml(t,f.name);toast('XML lido. A revisão já está pronta.');view('audit')}catch(e){console.error(e);toast('Não consegui ler esse XML.')}}
async function pdfText(f){try{const pdfjs=await import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs');pdfjs.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs';const pdf=await pdfjs.getDocument({data:new Uint8Array(await f.arrayBuffer())}).promise;let t='';for(let i=1;i<=Math.min(pdf.numPages,6);i++){const p=await pdf.getPage(i),c=await p.getTextContent();t+=' '+c.items.map(x=>x.str).join(' ')}return t.slice(0,40000)}catch{return''}}
function classify(f,text=''){const t=norm(`${f.name} ${text}`),rules=[['banca',['banca examinadora','defesa','tese','dissertacao'],90],['orientacao',['orientacao','orientador','orientadora'],84],['evento',['certificamos','congresso','seminario','simposio','evento'],74],['artigo',['doi','journal','revista','article','artigo','issn'],80],['tecnica',['curso de curta duracao','ministrou','oficina'],77],['livro',['isbn','editora'],76],['projeto',['projeto de pesquisa','projeto de extensao'],77]];let type='tecnica',confidence=35;for(const [k,terms,c] of rules)if(terms.some(x=>t.includes(norm(x)))){type=k;confidence=c;break}let match=null,best=0;for(const p of S.items.filter(x=>!x.removed)){const w=norm(p.title).split(' ').filter(x=>x.length>4);if(!w.length)continue;const r=w.filter(x=>t.includes(x)).length/Math.min(w.length,10);if(r>best){best=r;match=p}}return{classification:LABEL[type],confidence:Math.max(confidence,Math.round(best*100)),match:best>=.42?match:null}}
async function addFiles(files){for(const f of files){let text='';if(f.type==='text/plain'||f.name.endsWith('.txt'))text=await f.text();else if(f.type==='application/pdf'||f.name.toLowerCase().endsWith('.pdf'))text=await pdfText(f);const c=classify(f,text);S.files.unshift({id:uid(),name:f.name,size:f.size,type:f.type,classification:c.classification,confidence:c.confidence,match:c.match,status:c.match?'matched':text?'new':'review'})}render();toast(`${files.length} comprovante(s) adicionado(s).`)}
function demo(){const xml=`<?xml version="1.0" encoding="UTF-8"?><CURRICULO-VITAE NUMERO-IDENTIFICADOR="0000000000000000" DATA-ATUALIZACAO="17092026"><DADOS-GERAIS NOME-COMPLETO="Marina Silva"/><PRODUCAO-BIBLIOGRAFICA><ARTIGOS-PUBLICADOS><ARTIGO-PUBLICADO><DADOS-BASICOS-DO-ARTIGO TITULO-DO-ARTIGO="Mudanças climáticas e vulnerabilidade socioambiental em cidades brasileiras" ANO-DO-ARTIGO="2026" DOI="10.1234/demo.2026.01"/><DETALHAMENTO-DO-ARTIGO TITULO-DO-PERIODICO-OU-REVISTA="Journal of Environmental Studies" ISSN="12345678"/></ARTIGO-PUBLICADO><ARTIGO-PUBLICADO><DADOS-BASICOS-DO-ARTIGO TITULO-DO-ARTIGO="Dinâmica hidrológica de áreas úmidas tropicais" ANO-DO-ARTIGO="2025" DOI=""/><DETALHAMENTO-DO-ARTIGO TITULO-DO-PERIODICO-OU-REVISTA="Wetlands Ecology"/></ARTIGO-PUBLICADO><ARTIGO-PUBLICADO><DADOS-BASICOS-DO-ARTIGO TITULO-DO-ARTIGO="Mudanças climáticas e vulnerabilidade socioambiental em cidades brasileiras" ANO-DO-ARTIGO="2026" DOI="10.1234/demo.2026.01"/><DETALHAMENTO-DO-ARTIGO TITULO-DO-PERIODICO-OU-REVISTA="Journal of Environmental Studies" ISSN="12345678"/></ARTIGO-PUBLICADO></ARTIGOS-PUBLICADOS></PRODUCAO-BIBLIOGRAFICA></CURRICULO-VITAE>`;parseXml(xml,'curriculo_demo.xml');S.demo=true;toast('Demo carregada.');view('audit')}
function render(){dashboard();profile();categories();table();filesMini();filesList();renderReviewProgress();renderReview();renderAllAlerts();renderReport();$('navEvidenceBadge').textContent=S.files.length;$('navAuditBadge').textContent=openIssues().length;$('navChangeBadge').textContent=S.changes.length;lucide.createIcons()}
function dashboard(){const active=S.items.filter(x=>!x.removed),open=openIssues();$('statProductions').textContent=active.length;$('statIssues').textContent=open.length;$('statChanges').textContent=S.changes.length;$('statDuplicates').textContent=open.filter(x=>x.kind==='duplicate').length;$('scoreValue').textContent=S.score==null?'—':`${S.score}%`;$('scoreRing').style.setProperty('--score',S.score||0);$('scoreCaption').textContent=S.score==null?'Sem análise ainda':S.score>=90?'Currículo muito bem organizado':S.score>=75?'Quase lá':'Há melhorias rápidas disponíveis';if(S.researcher){$('heroStatus').className='status-pill '+(open.length?'warn':'good');$('heroStatus').innerHTML=`<span class="dot"></span>${open.length?`${open.length} pontos preparados para revisão`:'Nenhum alerta aberto'}`;$('heroHeadline').textContent=`${S.researcher.name.split(/\s+/)[0]}, vamos limpar seu Lattes.`;$('heroText').textContent=open.length?`Você não precisa revisar uma lista enorme. Vamos resolver um item por vez e montar uma nova cópia do XML.`:`A revisão está concluída. Você pode baixar a cópia atualizada.`}const list=$('priorityList');list.className='priority-list'+(open.length?'':' empty-state');list.innerHTML=open.length?open.slice(0,4).map(x=>`<div class="priority-item"><div class="priority-icon ${x.severity}"><i data-lucide="${x.kind==='duplicate'?'copy':'wand-sparkles'}"></i></div><div><strong>${esc(x.title)}</strong><p>${esc(x.description)}</p></div><span class="severity-tag ${x.severity}">${sev(x.severity)}</span></div>`).join(''):`<i data-lucide="${S.xmlName?'shield-check':'scan-search'}"></i><p>${S.xmlName?'Sua fila de revisão está limpa.':'Importe o XML para gerar sua fila de revisão.'}</p>`}
function profile(){if(!S.researcher)return;$('researcherName').textContent=S.researcher.name;$('researcherMeta').textContent=S.researcher.id?`Identificador Lattes: ${S.researcher.id}`:'Identificador não localizado';$('lastUpdateLabel').textContent=`Última atualização: ${S.researcher.updated||'—'}`;$('xmlFileLabel').textContent=`Arquivo: ${S.xmlName}`;document.querySelector('.avatar').textContent=initials(S.researcher.name)}
function categories(){const c={};S.items.filter(x=>!x.removed).forEach(p=>c[p.type]=(c[p.type]||0)+1);$('categoryGrid').innerHTML=Object.entries(c).map(([k,v])=>`<div class="category-card"><div class="category-top"><div class="category-icon"><i data-lucide="${ICON[k]||'file'}"></i></div><span>${Math.round(v/Math.max(1,S.items.filter(x=>!x.removed).length)*100)}%</span></div><strong>${v}</strong><span>${LABEL[k]}</span></div>`).join('')||'<div class="empty-state" style="grid-column:1/-1;min-height:100px"><p>As categorias aparecerão aqui após a importação.</p></div>'}
function table(){const search=norm($('productionSearch')?.value||''),sel=$('productionFilter'),active=S.items.filter(x=>!x.removed),types=[...new Set(active.map(x=>x.type))];if(sel){const cur=sel.value;sel.innerHTML='<option value="all">Todos os tipos</option>'+types.map(t=>`<option value="${t}">${LABEL[t]}</option>`).join('');if([...sel.options].some(o=>o.value===cur))sel.value=cur}const filter=sel?.value||'all',rows=active.filter(p=>(filter==='all'||p.type===filter)&&(!search||norm(`${p.title} ${p.year} ${p.venue} ${p.doi}`).includes(search)));$('productionTable').innerHTML=rows.length?rows.map(p=>`<tr><td><span class="type-chip">${LABEL[p.type]}</span></td><td><div class="table-title">${esc(p.title)}</div><div class="table-sub">${esc(p.venue||p.doi||'Sem detalhe adicional')}</div></td><td>${esc(p.year||'—')}</td><td><span class="progress-line"><span style="width:${p.complete}%"></span></span>${p.complete}%</td><td><span class="state-chip ${p.complete>=80?'ok':p.complete>=60?'warn':'bad'}">${p.complete>=80?'OK':p.complete>=60?'Revisar':'Completar'}</span></td></tr>`).join(''):'<tr><td colspan="5" class="table-empty">Nenhum item encontrado.</td></tr>'}
function filesMini(){const box=$('recentEvidence');if(!S.files.length){box.className='evidence-mini empty-state';box.innerHTML='<i data-lucide="inbox"></i><p>Adicione certificados e PDFs. Eles entram na fila para comparação com seu Lattes.</p>';return}box.className='evidence-mini';box.innerHTML=S.files.slice(0,4).map(f=>`<div class="evidence-mini-row"><div class="file-icon"><i data-lucide="file-text"></i></div><div class="file-meta"><strong>${esc(f.name)}</strong><span>${esc(f.classification)} • ${f.confidence}%</span></div></div>`).join('')}
function filesList(){$('inboxCount').textContent=S.files.length;$('evidenceList').innerHTML=S.files.length?S.files.map(f=>`<div class="evidence-card"><div class="file-icon"><i data-lucide="file-text"></i></div><div><h4>${esc(f.name)}</h4><p>${Math.max(1,Math.round(f.size/1024))} KB ${f.match?`• possível correspondência: ${esc(short(f.match.title,60))}`:''}</p></div><div class="classification"><strong>${esc(f.classification)} • ${f.confidence}%</strong><div class="confidence"><span style="width:${f.confidence}%"></span></div></div><button class="icon-btn" data-remove-file="${f.id}"><i data-lucide="x"></i></button></div>`).join(''):'<div class="empty-state roomy"><i data-lucide="folder-open"></i><p>Nenhum comprovante adicionado.</p></div>'}
function renderReviewProgress(){const total=S.issues.length,done=S.issues.filter(x=>x.status!=='open').length,pct=total?Math.round(done/total*100):S.xmlName?100:0;$('reviewProgressPct').textContent=`${pct}%`;$('reviewProgressBar').style.width=`${pct}%`;$('reviewProgressTitle').textContent=!S.xmlName?'Importe um XML para começar':total?`${done} de ${total} decisões concluídas`:'Nenhuma pendência encontrada';$('reviewProgressText').textContent=S.xmlName?`${openIssues().length} item(ns) ainda precisam de uma decisão rápida. ${S.changes.length} alteração(ões) já foram aplicadas à cópia.`:'As correções aprovadas serão aplicadas em uma cópia local do seu XML.'}
function renderReview(){const box=$('reviewWorkspace'),open=openIssues();if(!S.xmlName){box.className='review-workspace empty-state roomy';box.innerHTML='<i data-lucide="wand-sparkles"></i><p>Importe seu XML e o Easy Lattes prepara a fila de correção.</p>';$('reviewNav').hidden=true;return}if(!open.length){box.className='review-workspace';box.innerHTML=`<div class="review-card"><div class="review-body empty-state roomy"><i data-lucide="party-popper"></i><h3>Fila concluída.</h3><p>Você resolveu todos os alertas atuais. A cópia corrigida está pronta para revisão e download.</p><button class="btn neon" data-go="report"><i data-lucide="download"></i>Ir para o XML corrigido</button></div></div>`;$('reviewNav').hidden=true;return}ensureCursor();const issue=open[S.cursor];box.className='review-workspace';box.innerHTML=issue.kind==='duplicate'?duplicateCard(issue):enrichCard(issue);$('reviewNav').hidden=open.length<=1;renderDots(open);if(issue.suggestion)renderSuggestionHints(issue)}
function duplicateCard(i){const r=i.item,k=i.keep;return `<article class="review-card"><div class="review-card-head"><div class="review-card-head-left"><div class="review-symbol high"><i data-lucide="copy"></i></div><div><div class="mini-label">${LABEL[r.type].toUpperCase()} • DUPLICIDADE</div><h3>Provavelmente você não precisa dos dois.</h3><p>${esc(i.description)} O Easy Lattes escolheu automaticamente o registro mais completo para manter.</p></div></div><div class="confidence-pill">${i.confidence}% confiança</div></div><div class="review-body"><div class="compare-label">ANTES → DEPOIS</div><div class="duplicate-grid"><div class="record-card keep"><div class="record-top"><span class="record-tag">MANTER</span><strong>${k.complete}% completo</strong></div><h4>${esc(k.title)}</h4><div class="record-meta"><span>${esc(k.year||'sem ano')}</span><span>${esc(k.doi||k.venue||'sem identificador')}</span></div></div><div class="compare-arrow"><i data-lucide="arrow-right"></i></div><div class="record-card remove"><div class="record-top"><span class="record-tag">REMOVER</span><strong>${r.complete}% completo</strong></div><h4>${esc(r.title)}</h4><div class="record-meta"><span>${esc(r.year||'sem ano')}</span><span>${esc(r.doi||r.venue||'sem identificador')}</span></div></div></div></div><div class="review-actions"><div class="review-actions-left"><button class="btn ghost" id="swapDuplicateBtn"><i data-lucide="arrow-left-right"></i>Trocar qual fica</button><button class="btn ghost" id="keepBothBtn">Manter os dois</button></div><div class="review-actions-right"><button class="btn neon" id="acceptDuplicateBtn"><i data-lucide="check"></i>Aceitar e continuar</button></div></div></article>`}
function enrichCard(i){const p=i.item,s=i.suggestion||{};const field=(k,label)=>`<div class="field-card"><label>${label}</label><input id="fix-${k}" value="${esc(p[k]||'')}" placeholder="${k==='doi'?'10.xxxx/...':k==='year'?'2026':'Periódico / instituição'}"><div class="field-hint">${p[k]?'Valor atual do XML':'Campo vazio no XML'}</div></div>`;return `<article class="review-card"><div class="review-card-head"><div class="review-card-head-left"><div class="review-symbol ${i.severity}"><i data-lucide="wand-sparkles"></i></div><div><div class="mini-label">${LABEL[p.type].toUpperCase()} • COMPLETAR</div><h3>${esc(i.title)}</h3><p>${esc(short(p.title,160))}</p></div></div>${s.confidence?`<div class="confidence-pill">${s.confidence}% correspondência</div>`:''}</div><div class="review-body"><div class="compare-label">REVISE SÓ O NECESSÁRIO</div><div class="editor-grid">${field('doi','DOI')}${field('year','Ano')}${field('venue',p.type==='artigo'?'Periódico / revista':'Instituição / local')}</div>${p.type==='artigo'?`<div class="crossref-box"><div><strong>Posso procurar isso para você.</strong><p>Busca pelo título em uma base bibliográfica pública. Nenhuma chave de API é necessária.</p></div><button class="btn secondary" id="crossrefBtn"><i data-lucide="search"></i>Buscar dados do artigo</button></div>`:''}</div><div class="review-actions"><div class="review-actions-left"><button class="btn ghost" id="ignoreIssueBtn">Ignorar por enquanto</button>${s.confidence?'<button class="btn secondary" id="applySuggestionBtn"><i data-lucide="sparkles"></i>Preencher sugestões</button>':''}</div><div class="review-actions-right"><button class="btn neon" id="applyEnrichBtn"><i data-lucide="check"></i>Aplicar e continuar</button></div></div></article>`}
function renderDots(open){const box=$('reviewDots'),start=Math.max(0,S.cursor-8),end=Math.min(open.length,S.cursor+9);box.innerHTML=open.slice(start,end).map((_,idx)=>`<i class="${idx===S.cursor-start?'active':''}"></i>`).join('')}
function renderAllAlerts(){const box=$('auditList');$('allAlertsCount').textContent=S.issues.length;box.innerHTML=S.issues.length?S.issues.map(i=>`<div class="audit-row ${i.status!=='open'?'resolved':''}"><i data-lucide="${i.status==='open'?'circle-alert':'circle-check'}"></i><div><strong>${esc(i.title)}</strong><p>${esc(i.description)}</p></div><span class="severity-tag ${i.severity}">${i.status==='open'?sev(i.severity):i.status==='ignored'?'Ignorado':'Resolvido'}</span></div>`).join(''):'<div class="empty-state"><p>Nenhum alerta.</p></div>'}
function renderReport(){const total=S.issues.length,done=S.issues.filter(x=>x.status!=='open').length,pct=total?Math.round(done/total*100):S.xmlName?100:0;$('exportChangeCount').textContent=S.changes.length;$('exportProgress').textContent=`${pct}%`;$('exportStatus').textContent=S.changes.length?`${S.changes.length} alteração(ões) já estão na cópia de trabalho.`:'Nenhuma alteração aplicada ainda.';$('downloadXmlBtn').disabled=!S.doc;$('changeList').innerHTML=S.changes.length?S.changes.map(c=>`<div class="change-row"><div class="change-row-icon"><i data-lucide="check"></i></div><div><strong>${esc(c.title)}</strong><p>${esc(c.detail)}</p></div><time>${c.time.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</time></div>`).join(''):'<div class="empty-state"><i data-lucide="history"></i><p>As alterações aparecerão aqui conforme você aprovar as correções.</p></div>'}
function downloadXml(){if(!S.doc)return;let xml=new XMLSerializer().serializeToString(S.doc);if(!/^<\?xml/i.test(xml))xml=`<?xml version="1.0" encoding="UTF-8"?>\n${xml}`;const blob=new Blob([xml],{type:'application/xml;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`easy-lattes-corrigido-${new Date().toISOString().slice(0,10)}.xml`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('XML corrigido gerado. Revise antes de importar no Lattes.')}
function next(){const open=openIssues();if(open.length)S.cursor=Math.min(S.cursor+1,open.length-1);renderReview();lucide.createIcons()}
function prev(){if(S.cursor>0)S.cursor--;renderReview();lucide.createIcons()}
$$('.nav-item').forEach(b=>b.onclick=()=>view(b.dataset.view));document.addEventListener('click',e=>{const g=e.target.closest('[data-go]');if(g)view(g.dataset.go);const rm=e.target.closest('[data-remove-file]');if(rm){S.files=S.files.filter(f=>f.id!==rm.dataset.removeFile);render()}});
const choose=()=>{$('xmlInput').value='';$('xmlInput').click()};['openXmlBtn','heroXmlBtn','replaceXmlBtn'].forEach(id=>$(id).onclick=choose);$('xmlInput').onchange=e=>e.target.files[0]&&loadXml(e.target.files[0]);$('demoBtn').onclick=demo;$('startReviewBtn').onclick=()=>S.xmlName?view('audit'):choose();
const evChoose=()=>{$('evidenceInput').value='';$('evidenceInput').click()};['addEvidenceMini','addEvidenceBtn','browseEvidenceBtn'].forEach(id=>$(id).onclick=evChoose);$('evidenceInput').onchange=e=>addFiles([...e.target.files]);$('clearEvidenceBtn').onclick=()=>{S.files=[];render()};const dz=$('dropzone');['dragenter','dragover'].forEach(x=>dz.addEventListener(x,e=>{e.preventDefault();dz.classList.add('drag')}));['dragleave','drop'].forEach(x=>dz.addEventListener(x,e=>{e.preventDefault();dz.classList.remove('drag')}));dz.addEventListener('drop',e=>addFiles([...e.dataTransfer.files]));
$('productionSearch').oninput=table;$('productionFilter').onchange=table;$('rerunAuditBtn').onclick=()=>{audit(false);render();toast('Auditoria recalculada.')};$('safeFixBtn').onclick=applySafeFixes;$('prevIssueBtn').onclick=prev;$('nextIssueBtn').onclick=next;$('downloadXmlBtn').onclick=downloadXml;
document.addEventListener('click',e=>{const issue=openIssues()[S.cursor];if(!issue)return;if(e.target.closest('#acceptDuplicateBtn'))applyDuplicate(issue);if(e.target.closest('#keepBothBtn'))keepBoth(issue);if(e.target.closest('#swapDuplicateBtn'))swapDuplicate(issue);if(e.target.closest('#ignoreIssueBtn'))resolveIssue(issue,'ignored');if(e.target.closest('#applyEnrichBtn'))applyEnrich(issue);if(e.target.closest('#crossrefBtn'))lookupCrossref(issue);if(e.target.closest('#applySuggestionBtn'))applySuggestion(issue)});
render();lucide.createIcons();