const S={xml:null,researcher:null,items:[],issues:[],files:[],score:null,auditFilter:'all'};
const $=id=>document.getElementById(id), $$=q=>[...document.querySelectorAll(q)];
const LABEL={artigo:'Artigo',livro:'Livro',capitulo:'Capítulo',orientacao:'Orientação',banca:'Banca',evento:'Evento',projeto:'Projeto',tecnica:'Produção técnica'};
const ICON={artigo:'newspaper',livro:'book-open',capitulo:'book-copy',orientacao:'graduation-cap',banca:'users',evento:'calendar-days',projeto:'flask-conical',tecnica:'wrench'};
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const norm=s=>String(s??'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
const attr=(e,n)=>e?.getAttribute?.(n)||'';
const child=(e,s,n)=>attr(e.querySelector(s),n);
const short=s=>String(s||'').length>72?String(s).slice(0,69)+'…':String(s||'');
const initials=n=>String(n||'?').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase();
const sev=s=>s==='high'?'Crítico':s==='medium'?'Atenção':'Sugestão';
function toast(m){const d=document.createElement('div');d.className='toast';d.textContent=m;$('toastStack').appendChild(d);setTimeout(()=>d.remove(),2800)}
function view(name){$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));const t={dashboard:'Seu currículo, sob controle.',lattes:'Seu Lattes, decodificado.',inbox:'Sua caixa acadêmica.',audit:'Auditoria inteligente.',report:'Seu plano de revisão.'};$('pageTitle').textContent=t[name]||'Easy Lattes';scrollTo({top:0,behavior:'smooth'})}
function item(type,data,id){const title=(data.title||'').trim(),year=(data.year||'').trim(),doi=(data.doi||'').trim(),venue=(data.venue||'').trim(),extra=(data.extra||'').trim();const checks=[!!title,!!year,!!venue,type==='artigo'?!!(doi||extra):true];return{id,type,title:title||'(sem título identificado)',year,doi,venue,extra,complete:Math.round(checks.filter(Boolean).length/checks.length*100)}}
function generic(el){const a={};[el,...el.querySelectorAll('*')].forEach(n=>[...n.attributes].forEach(x=>a[x.name]=x.value));const first=ks=>ks.find(k=>a[k])?a[ks.find(k=>a[k])]||'':'';return{title:first(['TITULO','TITULO-DO-TRABALHO','TITULO-DA-ORIENTACAO','NOME-DO-EVENTO','TITULO-DO-TRABALHO-TECNICO','TITULO-DO-CURSO-DE-CURTA-DURACAO']),year:first(['ANO','ANO-DA-ORIENTACAO','ANO-DO-TRABALHO','ANO-DO-EVENTO']),venue:first(['NOME-DA-INSTITUICAO','NOME-INSTITUICAO','NOME-DA-ENTIDADE','NOME-DO-EVENTO','NOME-DO-CURSO'])}}
function collect(doc,selector,type,map){[...doc.querySelectorAll(selector)].forEach((e,i)=>S.items.push(item(type,map(e),selector+i)))}
function parseXml(text,name='curriculo.xml'){
 const doc=new DOMParser().parseFromString(text,'application/xml');if(doc.querySelector('parsererror'))throw Error('XML inválido');const root=doc.querySelector('CURRICULO-VITAE')||doc.documentElement,d=doc.querySelector('DADOS-GERAIS');S.xml=name;S.researcher={name:attr(d,'NOME-COMPLETO')||'Pesquisador',id:attr(root,'NUMERO-IDENTIFICADOR'),updated:attr(root,'DATA-ATUALIZACAO')};S.items=[];
 collect(doc,'ARTIGO-PUBLICADO','artigo',e=>({title:child(e,'DADOS-BASICOS-DO-ARTIGO','TITULO-DO-ARTIGO'),year:child(e,'DADOS-BASICOS-DO-ARTIGO','ANO-DO-ARTIGO'),doi:child(e,'DADOS-BASICOS-DO-ARTIGO','DOI'),venue:child(e,'DETALHAMENTO-DO-ARTIGO','TITULO-DO-PERIODICO-OU-REVISTA'),extra:child(e,'DETALHAMENTO-DO-ARTIGO','ISSN')}));
 collect(doc,'LIVRO-PUBLICADO-OU-ORGANIZADO','livro',e=>({title:child(e,'DADOS-BASICOS-DO-LIVRO','TITULO-DO-LIVRO'),year:child(e,'DADOS-BASICOS-DO-LIVRO','ANO'),doi:child(e,'DADOS-BASICOS-DO-LIVRO','DOI'),venue:child(e,'DETALHAMENTO-DO-LIVRO','NOME-DA-EDITORA'),extra:child(e,'DETALHAMENTO-DO-LIVRO','ISBN')}));
 collect(doc,'CAPITULO-DE-LIVRO-PUBLICADO','capitulo',e=>({title:child(e,'DADOS-BASICOS-DO-CAPITULO','TITULO-DO-CAPITULO-DO-LIVRO'),year:child(e,'DADOS-BASICOS-DO-CAPITULO','ANO'),doi:child(e,'DADOS-BASICOS-DO-CAPITULO','DOI'),venue:child(e,'DETALHAMENTO-DO-CAPITULO','TITULO-DO-LIVRO'),extra:child(e,'DETALHAMENTO-DO-CAPITULO','ISBN')}));
 const groups={orientacao:['ORIENTACOES-CONCLUIDAS-PARA-MESTRADO','ORIENTACOES-CONCLUIDAS-PARA-DOUTORADO','OUTRAS-ORIENTACOES-CONCLUIDAS'],banca:['PARTICIPACAO-EM-BANCA-DE-MESTRADO','PARTICIPACAO-EM-BANCA-DE-DOUTORADO','PARTICIPACAO-EM-BANCA-DE-TRABALHOS-DE-CONCLUSAO'],evento:['PARTICIPACAO-EM-CONGRESSO','PARTICIPACAO-EM-SEMINARIO','PARTICIPACAO-EM-SIMPOSIO','PARTICIPACAO-EM-ENCONTRO'],tecnica:['TRABALHO-TECNICO','CURSO-DE-CURTA-DURACAO-MINISTRADO','ORGANIZACAO-DE-EVENTO']};Object.entries(groups).forEach(([t,ss])=>ss.forEach(s=>collect(doc,s,t,generic)));collect(doc,'PROJETO-DE-PESQUISA','projeto',e=>({title:attr(e,'NOME-DO-PROJETO'),year:attr(e,'ANO-INICIO'),venue:attr(e,'DESCRICAO-DO-PROJETO')}));audit();render();
}
function audit(){const seen=new Map(),out=[];for(const p of S.items){if(!p.year)out.push({severity:'medium',title:'Ano ausente',description:`${short(p.title)} está sem ano identificado.`,type:p.type});if(p.type==='artigo'&&!p.doi)out.push({severity:'medium',title:'Artigo sem DOI',description:`${short(p.title)} não apresenta DOI no XML. Vale conferir.`,type:p.type});if(p.complete<60)out.push({severity:'high',title:'Cadastro pouco completo',description:`${short(p.title)} tem poucos campos essenciais identificados.`,type:p.type});else if(p.complete<80)out.push({severity:'low',title:'Cadastro pode ser enriquecido',description:`${short(p.title)} possui campos que podem ser conferidos.`,type:p.type});const k=norm(p.title);if(k.length>12){if(seen.has(k))out.push({severity:'high',title:'Possível duplicidade',description:`Dois itens têm o mesmo título: “${short(p.title)}”.`,type:p.type});else seen.set(k,p)}}S.issues=out;const avg=S.items.length?S.items.reduce((a,p)=>a+p.complete,0)/S.items.length:0,pen=Math.min(25,out.filter(x=>x.severity==='high').length*4+out.filter(x=>x.severity==='medium').length*1.5);S.score=S.items.length?Math.max(0,Math.round(avg-pen)):null}
async function loadXml(f){try{const b=await f.arrayBuffer();let t=new TextDecoder().decode(b);if(/8859-1|windows-1252/i.test(t.slice(0,160)))t=new TextDecoder('windows-1252').decode(b);parseXml(t,f.name);toast('XML lido com sucesso.');view('dashboard')}catch(e){console.error(e);toast('Não consegui ler esse XML.')}}
async function pdfText(f){try{const pdfjs=await import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs');pdfjs.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs';const pdf=await pdfjs.getDocument({data:new Uint8Array(await f.arrayBuffer())}).promise;let t='';for(let i=1;i<=Math.min(pdf.numPages,6);i++){const p=await pdf.getPage(i),c=await p.getTextContent();t+=' '+c.items.map(x=>x.str).join(' ')}return t.slice(0,40000)}catch{return''}}
function classify(f,text=''){const t=norm(`${f.name} ${text}`),rules=[['banca',['banca examinadora','defesa','tese','dissertacao'],90],['orientacao',['orientacao','orientador','orientadora'],82],['evento',['certificamos','congresso','seminario','simposio','evento'],72],['artigo',['doi','journal','revista','article','artigo','issn'],78],['tecnica',['curso de curta duracao','ministrou','oficina'],76],['livro',['isbn','editora'],75],['projeto',['projeto de pesquisa','projeto de extensao'],76]];let type='tecnica',confidence=35;for(const [k,terms,c] of rules)if(terms.some(x=>t.includes(norm(x)))){type=k;confidence=c;break}let match=null,best=0;for(const p of S.items){const w=norm(p.title).split(' ').filter(x=>x.length>4);if(!w.length)continue;const r=w.filter(x=>t.includes(x)).length/Math.min(w.length,10);if(r>best){best=r;match=p}}return{classification:LABEL[type],confidence:Math.max(confidence,Math.round(best*100)),match:best>=.38?match:null}}
async function addFiles(files){for(const f of files){let text='';if(f.type==='text/plain'||f.name.endsWith('.txt'))text=await f.text();else if(f.type==='application/pdf'||f.name.toLowerCase().endsWith('.pdf'))text=await pdfText(f);const c=classify(f,text);S.files.unshift({id:crypto.randomUUID(),name:f.name,size:f.size,type:f.type,classification:c.classification,confidence:c.confidence,match:c.match,status:c.match?'matched':text?'new':'review'})}render();toast(`${files.length} comprovante(s) adicionado(s).`)}
function demo(){S.xml='curriculo_demo.xml';S.researcher={name:'Prof.ª Marina Silva',id:'0000000000000000',updated:'15092026'};S.items=[item('artigo',{title:'Mudanças climáticas e vulnerabilidade socioambiental em cidades brasileiras',year:'2026',doi:'10.1234/demo.2026.01',venue:'Journal of Environmental Studies',extra:'1234-5678'},'1'),item('artigo',{title:'Dinâmica hidrológica de áreas úmidas tropicais',year:'2025',venue:'Wetlands Ecology'},'2'),item('orientacao',{title:'Vulnerabilidade climática em municípios do Centro-Oeste',year:'2026',venue:'Universidade Federal'},'3'),item('banca',{title:'Análise da qualidade ambiental em bacias urbanas',year:'2025',venue:'Programa de Pós-Graduação'},'4'),item('evento',{title:'Congresso Brasileiro de Ciências Ambientais',year:'2026',venue:'Cuiabá'},'5'),item('artigo',{title:'Dinâmica hidrológica de áreas úmidas tropicais',year:'2025',venue:'Wetlands Ecology'},'6')];audit();render();toast('Demo carregada.')}
function render(){dashboard();profile();categories();table();filesMini();filesList();auditView();report();$('navEvidenceBadge').textContent=S.files.length;$('navAuditBadge').textContent=S.issues.length;lucide.createIcons()}
function dashboard(){const score=S.score,issues=S.issues.length;$('statProductions').textContent=S.items.length;$('statIssues').textContent=issues;$('statEvidence').textContent=S.files.length;$('statDuplicates').textContent=S.issues.filter(x=>x.title==='Possível duplicidade').length;$('scoreValue').textContent=score==null?'—':`${score}%`;$('scoreRing').style.setProperty('--score',score||0);$('scoreCaption').textContent=score==null?'Sem análise ainda':score>=85?'Currículo bem organizado':score>=65?'Alguns pontos merecem revisão':'Revisão recomendada';if(S.researcher){$('heroHeadline').textContent=`${S.researcher.name.split(/\s+/).filter(x=>!/^prof/i.test(x))[0]}, seu currículo está ${score??0}% em dia.`;$('heroText').textContent=`Encontramos ${issues} alerta(s) automáticos e ${S.files.length} comprovante(s) na sua caixa acadêmica.`}const list=$('priorityList');list.className='priority-list'+(issues?'':' empty-state');list.innerHTML=issues?S.issues.slice(0,5).map(x=>`<div class="priority-item"><div class="priority-icon ${x.severity}"><i data-lucide="triangle-alert"></i></div><div><strong>${esc(x.title)}</strong><p>${esc(x.description)}</p></div><span class="severity-tag ${x.severity}">${sev(x.severity)}</span></div>`).join(''):`<i data-lucide="${S.xml?'shield-check':'scan-search'}"></i><p>${S.xml?'Nenhuma pendência encontrada pelas regras atuais.':'Importe o XML do Lattes para gerar sua primeira auditoria.'}</p>`}
function profile(){if(!S.researcher)return;$('researcherName').textContent=S.researcher.name;$('researcherMeta').textContent=S.researcher.id?`Identificador Lattes: ${S.researcher.id}`:'Identificador não localizado';$('lastUpdateLabel').textContent=`Última atualização: ${S.researcher.updated||'—'}`;$('xmlFileLabel').textContent=`Arquivo: ${S.xml}`;document.querySelector('.avatar').textContent=initials(S.researcher.name)}
function categories(){const c={};S.items.forEach(p=>c[p.type]=(c[p.type]||0)+1);$('categoryGrid').innerHTML=Object.entries(c).map(([k,v])=>`<div class="category-card"><div class="category-top"><div class="category-icon"><i data-lucide="${ICON[k]||'file'}"></i></div><span>${Math.round(v/Math.max(1,S.items.length)*100)}%</span></div><strong>${v}</strong><span>${LABEL[k]}</span></div>`).join('')||'<div class="empty-state" style="grid-column:1/-1;min-height:100px"><p>As categorias aparecerão aqui após a importação.</p></div>'}
function table(){const search=norm($('productionSearch')?.value||''),sel=$('productionFilter');const types=[...new Set(S.items.map(x=>x.type))];if(sel){const cur=sel.value;sel.innerHTML='<option value="all">Todos os tipos</option>'+types.map(t=>`<option value="${t}">${LABEL[t]}</option>`).join('');if([...sel.options].some(o=>o.value===cur))sel.value=cur}const filter=sel?.value||'all',rows=S.items.filter(p=>(filter==='all'||p.type===filter)&&(!search||norm(`${p.title} ${p.year} ${p.venue} ${p.doi}`).includes(search)));$('productionTable').innerHTML=rows.length?rows.map(p=>`<tr><td><span class="type-chip">${LABEL[p.type]}</span></td><td><div class="table-title">${esc(p.title)}</div><div class="table-sub">${esc(p.venue||p.doi||'Sem detalhe adicional')}</div></td><td>${esc(p.year||'—')}</td><td><span class="progress-line"><span style="width:${p.complete}%"></span></span>${p.complete}%</td><td><span class="state-chip ${p.complete>=80?'ok':p.complete>=60?'warn':'bad'}">${p.complete>=80?'OK':p.complete>=60?'Revisar':'Incompleto'}</span></td></tr>`).join(''):'<tr><td colspan="5" class="table-empty">Nenhum item encontrado.</td></tr>'}
function filesMini(){const b=$('recentEvidence');b.className='evidence-mini'+(S.files.length?'':' empty-state');b.innerHTML=S.files.length?S.files.slice(0,5).map(f=>`<div class="evidence-mini-row"><div class="file-icon"><i data-lucide="file-text"></i></div><div class="file-meta"><strong>${esc(f.name)}</strong><span>${esc(f.classification)} • ${f.match?'possível vínculo encontrado':f.status}</span></div><span class="state-chip ${f.match?'ok':'warn'}">${f.confidence}%</span></div>`).join(''):'<i data-lucide="inbox"></i><p>Arraste certificados, PDFs ou imagens. O sistema tenta classificar cada item.</p>'}
function filesList(){const b=$('evidenceList'),filter=$('evidenceFilter')?.value||'all',arr=S.files.filter(f=>filter==='all'||f.status===filter);$('inboxCount').textContent=S.files.length;b.innerHTML=arr.length?arr.map(f=>`<div class="evidence-card"><div class="file-icon"><i data-lucide="file-text"></i></div><div><h4>${esc(f.name)}</h4><p>${Math.round(f.size/1024)} KB • ${f.match?'possível correspondência: '+esc(short(f.match.title)):f.status}</p></div><div class="classification"><strong>${esc(f.classification)}</strong><div class="confidence"><span style="width:${f.confidence}%"></span></div><p>${f.confidence}% de confiança heurística</p></div><div class="evidence-actions"><button class="icon-btn" data-remove="${f.id}"><i data-lucide="trash-2"></i></button></div></div>`).join(''):'<div class="empty-state roomy"><i data-lucide="folder-open"></i><p>Nenhum comprovante nesta visualização.</p></div>';$$('[data-remove]').forEach(x=>x.onclick=()=>{S.files=S.files.filter(f=>f.id!==x.dataset.remove);render()})}
function auditView(){const counts={high:0,medium:0,low:0};S.issues.forEach(i=>counts[i.severity]++);$('auditScore').textContent=S.score==null?'—':`${S.score}%`;$('auditBars').innerHTML=['high','medium','low'].map(s=>`<div class="audit-bar-item"><span>${s==='high'?'CRÍTICOS':s==='medium'?'ATENÇÃO':'SUGESTÕES'}</span><strong>${counts[s]}</strong><div class="bar-track"><i style="width:${Math.min(100,counts[s]*18)}%"></i></div></div>`).join('');const a=S.issues.filter(i=>S.auditFilter==='all'||i.severity===S.auditFilter);$('auditList').innerHTML=a.length?a.map(i=>`<div class="audit-card"><div class="priority-icon ${i.severity}"><i data-lucide="triangle-alert"></i></div><div><h4>${esc(i.title)}</h4><p>${esc(i.description)}</p><div class="audit-meta">${LABEL[i.type]||'Currículo'} • revisão humana recomendada</div></div><span class="severity-tag ${i.severity}">${sev(i.severity)}</span></div>`).join(''):`<div class="empty-state roomy"><i data-lucide="shield-check"></i><p>${S.xml?'Nenhum alerta nesta categoria.':'Importe um XML para gerar alertas.'}</p></div>`}
function report(){$('reportCompleteness').textContent=S.score==null?'—':`${S.score}%`;$('reportIssues').textContent=S.issues.length;$('reportEvidence').textContent=S.files.length;const t=[];if(S.issues.some(i=>i.severity==='high'))t.push(['Revisar alertas críticos','Existem possíveis duplicidades ou cadastros muito incompletos.']);if(S.issues.length)t.push(['Conferir campos ausentes','Revise DOI, ano e demais campos sinalizados.']);if(S.files.length)t.push(['Validar comprovantes',`${S.files.length} arquivo(s) foram recebidos.`]);if(S.xml)t.push(['Atualizar no sistema oficial','Após conferir os dados, faça as alterações necessárias diretamente na Plataforma Lattes.']);$('reportChecklist').innerHTML=t.length?t.map(([a,b])=>`<div class="check-row"><div class="check-circle"><i data-lucide="check"></i></div><div><strong>${a}</strong><p>${b}</p></div></div>`).join(''):'<div class="empty-state"><p>O checklist aparecerá após a análise.</p></div>'}
function csv(){if(!S.xml&&!S.files.length)return toast('Nada para exportar ainda.');const rows=[['SECAO','TIPO','TITULO/ARQUIVO','ANO','STATUS','DETALHE']];S.items.forEach(p=>rows.push(['LATTES',LABEL[p.type],p.title,p.year,`${p.complete}% completo`,p.doi||p.venue]));S.issues.forEach(i=>rows.push(['AUDITORIA',sev(i.severity),i.title,'',i.severity,i.description]));S.files.forEach(f=>rows.push(['COMPROVANTE',f.classification,f.name,'',f.status,f.match?`Possível vínculo: ${f.match.title}`:'']));const text='\ufeff'+rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(';')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv'}));a.download='relatorio_easy_lattes.csv';a.click();URL.revokeObjectURL(a.href)}
function bind(){$$('.nav-item').forEach(b=>b.onclick=()=>view(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>view(b.dataset.go));['openXmlBtn','heroXmlBtn','replaceXmlBtn'].forEach(id=>$(id).onclick=()=>$('xmlInput').click());$('xmlInput').onchange=e=>e.target.files[0]&&loadXml(e.target.files[0]);['heroEvidenceBtn','addEvidenceMini','addEvidenceBtn','browseEvidenceBtn'].forEach(id=>$(id).onclick=()=>$('evidenceInput').click());$('evidenceInput').onchange=e=>addFiles([...e.target.files]);$('demoBtn').onclick=demo;$('rerunAuditBtn').onclick=()=>{audit();render();toast('Auditoria atualizada.')};$('clearEvidenceBtn').onclick=()=>{S.files=[];render()};$('downloadReportBtn').onclick=csv;$('productionSearch').oninput=table;$('productionFilter').onchange=table;$('evidenceFilter').onchange=filesList;$$('#auditSegments button').forEach(b=>b.onclick=()=>{S.auditFilter=b.dataset.severity;$$('#auditSegments button').forEach(x=>x.classList.toggle('active',x===b));auditView();lucide.createIcons()});const dz=$('dropzone');['dragenter','dragover'].forEach(x=>dz.addEventListener(x,e=>{e.preventDefault();dz.classList.add('drag')}));['dragleave','drop'].forEach(x=>dz.addEventListener(x,e=>{e.preventDefault();dz.classList.remove('drag')}));dz.addEventListener('drop',e=>addFiles([...e.dataTransfer.files]))}
bind();render();
