(() => {
  const q=(s,r=document)=>r.querySelector(s), qa=(s,r=document)=>[...r.querySelectorAll(s)];
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
  const uid=()=>crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`;
  const D={results:[],ignored:new Set(),running:false,author:null,lastMeta:null};

  function toast(msg){const stack=q('#toastStack');if(!stack)return;const d=document.createElement('div');d.className='toast';d.textContent=msg;stack.appendChild(d);setTimeout(()=>d.remove(),3500)}
  function currentDoc(){return window.__easyLattesCurrentDoc||null}
  function firstAttr(doc,names){for(const el of qa('*',doc))for(const n of names){const v=el.getAttribute?.(n);if(v)return v}return''}
  function profile(){const doc=currentDoc();if(!doc)return{name:'',institution:'',orcid:''};const dg=doc.querySelector('DADOS-GERAIS');const name=dg?.getAttribute('NOME-COMPLETO')||'';const orcid=dg?.getAttribute('ORCID-ID')||firstAttr(doc,['ORCID-ID','ORCID']);let institution='';for(const a of ['NOME-INSTITUICAO','NOME-INSTITUICAO-EMPRESA','NOME-DA-INSTITUICAO']){institution=firstAttr(doc,[a]);if(institution)break}return{name,institution,orcid}}
  function xmlTitles(){const doc=currentDoc();if(!doc)return[];const attrs=['TITULO-DO-ARTIGO','TITULO-DO-LIVRO','TITULO-DO-CAPITULO-DO-LIVRO','TITULO','NOME-DO-PROJETO','NOME-DO-EVENTO'];const out=[];qa('*',doc).forEach(el=>attrs.forEach(a=>{const v=el.getAttribute?.(a);if(v&&v.length>8)out.push(v)}));return out}
  function sim(a,b){const A=new Set(norm(a).split(' ').filter(x=>x.length>2)),B=new Set(norm(b).split(' ').filter(x=>x.length>2));if(!A.size||!B.size)return 0;let i=0;A.forEach(x=>{if(B.has(x))i++});return 2*i/(A.size+B.size)}
  function existsInXml(title){if(!title)return false;return xmlTitles().some(x=>sim(x,title)>=.78)}
  function category(text){const t=norm(text);if(/banca|defesa|dissertacao|tese|avaliador|examinadora/.test(t))return'banca';if(/curso|minicurso|oficina|capacitacao|formacao/.test(t))return'curso';if(/palestra|palestrante|conferencia|mesa redonda|apresentacao/.test(t))return'apresentacao';if(/disciplina|docente|professor|ensino/.test(t))return'disciplina';if(/congresso|seminario|simposio|encontro|evento/.test(t))return'evento';if(/premio|premiacao|homenagem/.test(t))return'premio';if(/artigo|journal|doi|paper|revista/.test(t))return'artigo';return'outra'}
  function yearFrom(value){const m=String(value||'').match(/\b(19|20)\d{2}\b/);return m?m[0]:''}
  function sourceHost(url){try{return new URL(url).hostname.replace(/^www\./,'')}catch{return''}}
  function normalizeResult(r){return{id:r.id||uid(),title:String(r.title||'').trim(),year:String(r.year||''),url:r.url||'',source:r.source||sourceHost(r.url)||'web',kind:r.kind||category(`${r.title||''} ${r.snippet||''}`),snippet:String(r.snippet||'').trim(),doi:r.doi||'',confidence:Number(r.confidence||0),status:r.status||'new',existing:existsInXml(r.title),evidence:r.evidence||'',institution:r.institution||''}}
  function dedupe(items){const map=new Map();for(const raw of items){const r=normalizeResult(raw);const key=r.doi?`doi:${norm(r.doi)}`:`t:${norm(r.title)}`;if(!r.title||D.ignored.has(key))continue;const prev=map.get(key);if(!prev||r.confidence>prev.confidence)map.set(key,r)}return [...map.values()]}

  async function searchOpenAlex(name,institution){
    const out=[];
    try{
      const ar=await fetch(`https://api.openalex.org/authors?search=${encodeURIComponent(name)}&per-page=6`);if(!ar.ok)throw Error('OpenAlex authors');const aj=await ar.json();const authors=(aj.results||[]).map(a=>{const inst=a.last_known_institutions?.[0]?.display_name||a.last_known_institution?.display_name||'';let score=sim(name,a.display_name||'')*.75;if(institution&&inst)score+=sim(institution,inst)*.25;return{a,score,inst}}).sort((x,y)=>y.score-x.score);const best=authors[0];if(!best||best.score<.56)return out;D.author={name:best.a.display_name||name,institution:best.inst,id:best.a.id,works:best.a.works_count||0,score:Math.round(best.score*100)};
      const id=String(best.a.id||'').split('/').pop();if(!id)return out;const wr=await fetch(`https://api.openalex.org/works?filter=author.id:${encodeURIComponent(id)}&per-page=50&sort=publication_date:desc`);if(!wr.ok)throw Error('OpenAlex works');const wj=await wr.json();for(const w of wj.results||[]){const title=w.display_name||w.title||'';const year=w.publication_year||yearFrom(w.publication_date);const doi=String(w.doi||'').replace(/^https?:\/\/doi.org\//,'');out.push({title,year,url:w.doi||w.primary_location?.landing_page_url||w.id,source:'OpenAlex',kind:'artigo',doi,confidence:Math.round(best.score*100),snippet:(w.primary_location?.source?.display_name||'')+(w.type?` • ${w.type}`:'')})}
    }catch(e){console.warn('OpenAlex',e)}
    return out;
  }
  async function searchCrossref(name){
    const out=[];
    try{const url=`https://api.crossref.org/works?rows=40&select=DOI,title,published,container-title,URL,author,type&query.author=${encodeURIComponent(name)}`;const r=await fetch(url);if(!r.ok)throw Error('Crossref');const j=await r.json();for(const w of j?.message?.items||[]){const authors=(w.author||[]).map(a=>`${a.given||''} ${a.family||''}`.trim());const nameScore=Math.max(0,...authors.map(a=>sim(a,name)));if(nameScore<.45)continue;const title=(w.title||[])[0]||'';const year=w.published?.['date-parts']?.[0]?.[0]||'';out.push({title,year,url:w.URL||`https://doi.org/${w.DOI}`,source:'Crossref',kind:'artigo',doi:w.DOI||'',confidence:Math.round(nameScore*100),snippet:(w['container-title']||[])[0]||w.type||''})}}
    catch(e){console.warn('Crossref',e)}return out;
  }
  async function searchBroadWeb(name,institution){
    const endpoint=window.EASY_LATTES_WEB_DISCOVERY_ENDPOINT||window.EASY_LATTES_CONFIG?.webDiscoveryEndpoint||'';
    if(!endpoint)return{results:[],unavailable:true};
    try{const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,institution})});if(!r.ok)throw Error(`web ${r.status}`);const j=await r.json();return{results:(j.results||[]).map(x=>({...x,source:x.source||sourceHost(x.url),confidence:x.confidence||70})),meta:j.meta||null}}
    catch(e){console.warn(e);return{results:[],error:true}}
  }

  async function runSearch(){
    if(D.running)return;const p=profile();const name=q('#discoveryName')?.value.trim()||p.name;const institution=q('#discoveryInstitution')?.value.trim()||p.institution;if(!name)return toast('Importe o XML ou informe o nome do pesquisador.');const consent=q('#discoveryConsent');if(!consent?.checked)return toast('Marque a autorização para pesquisar fontes públicas.');D.running=true;renderLoading();
    const [oa,cr,web]=await Promise.all([searchOpenAlex(name,institution),searchCrossref(name),searchBroadWeb(name,institution)]);D.lastMeta=web.meta||null;D.results=dedupe([...oa,...cr,...(web.results||[])]).sort((a,b)=>Number(a.existing)-Number(b.existing)||b.confidence-a.confidence||Number(b.year||0)-Number(a.year||0));D.running=false;render();if(web.unavailable)toast('Busca acadêmica concluída. A busca ampla na web ainda precisa do backend.');else toast(`Busca concluída: ${D.results.filter(x=>!x.existing).length} possível(is) item(ns) ausente(s).`)
  }
  function renderLoading(){const box=q('#discoveryResults');if(box)box.innerHTML=`<div class="discover-loading"><div class="discover-spinner"></div><div><strong>Vasculhando fontes públicas…</strong><p>Comparando resultados com os títulos que já existem no XML.</p></div></div>`}
  function reviewDiscovery(id){const r=D.results.find(x=>x.id===id);if(!r)return;const btn=q('#manualEntryBtn');if(!btn)return toast('A Caixa Acadêmica ainda não está disponível.');btn.click();setTimeout(()=>{const map={artigo:'outra',apresentacao:'apresentacao',curso:'curso',banca:'banca',evento:'evento',premio:'premio',disciplina:'outra',outra:'outra'};const set=(id,v)=>{const el=q(`#${id}`);if(el&&v!==undefined)el.value=v};set('intakeType',map[r.kind]||'outra');set('intakeTitle',r.title);set('intakeYear',r.year);set('intakeInstitution',r.institution);set('intakeNotes',`Fonte pública: ${r.source}${r.url?` — ${r.url}`:''}${r.snippet?`\n${r.snippet}`:''}`);},80)}
  function ignoreDiscovery(id){const r=D.results.find(x=>x.id===id);if(!r)return;D.ignored.add(r.doi?`doi:${norm(r.doi)}`:`t:${norm(r.title)}`);D.results=D.results.filter(x=>x.id!==id);render()}
  function openDiscovery(id){const r=D.results.find(x=>x.id===id);if(r?.url)window.open(r.url,'_blank','noopener,noreferrer')}

  function resultCard(r){const badge=r.existing?'Já aparece no XML':r.kind==='artigo'?'Possível publicação ausente':'Possível atividade ausente';return `<article class="discover-card ${r.existing?'existing':''}"><div class="discover-card-top"><div class="discover-type ${r.kind}"><i data-lucide="${r.kind==='artigo'?'newspaper':r.kind==='banca'?'graduation-cap':r.kind==='curso'?'book-open-check':r.kind==='apresentacao'?'mic-2':r.kind==='disciplina'?'school':'sparkles'}"></i></div><div class="discover-main"><div class="discover-meta"><span>${esc(r.source)}</span>${r.year?`<span>${esc(r.year)}</span>`:''}<span>${esc(badge)}</span></div><h4>${esc(r.title)}</h4>${r.snippet?`<p>${esc(r.snippet)}</p>`:''}</div><div class="discover-confidence"><strong>${Math.max(0,Math.min(100,Math.round(r.confidence||0)))}%</strong><span>correspondência</span></div></div><div class="discover-actions"><button class="btn ghost mini" data-discover-open="${r.id}"><i data-lucide="external-link"></i>Ver fonte</button>${r.existing?'<span class="already-pill"><i data-lucide="check"></i>provavelmente já cadastrado</span>':`<button class="btn ghost mini" data-discover-ignore="${r.id}">Não é meu</button><button class="btn neon mini" data-discover-review="${r.id}"><i data-lucide="plus"></i>Revisar e adicionar</button>`}</div></article>`}
  function render(){const box=q('#discoveryResults'),p=profile();if(q('#discoveryName')&&!q('#discoveryName').value&&p.name)q('#discoveryName').value=p.name;if(q('#discoveryInstitution')&&!q('#discoveryInstitution').value&&p.institution)q('#discoveryInstitution').value=p.institution;if(!box)return;const missing=D.results.filter(x=>!x.existing),existing=D.results.filter(x=>x.existing);q('#discoveryMissingCount').textContent=String(missing.length);q('#discoveryTotalCount').textContent=String(D.results.length);const author=q('#discoveryAuthorMatch');if(author){author.innerHTML=D.author?`<i data-lucide="badge-check"></i><div><strong>${esc(D.author.name)}</strong><span>${esc(D.author.institution||'afiliação não informada')} • ${D.author.score}% de correspondência</span></div>`:`<i data-lucide="circle-user"></i><div><strong>A identidade será conferida antes da busca</strong><span>Nome, instituição e ORCID ajudam a evitar homônimos.</span></div>`}
    if(!D.results.length){box.innerHTML=`<div class="discover-empty"><i data-lucide="search-check"></i><h4>O Easy Lattes pode procurar o que ficou para trás.</h4><p>Importe o XML, confira seu nome e clique em <strong>Vasculhar fontes públicas</strong>. Nenhum resultado é adicionado automaticamente.</p></div>`}else{box.innerHTML=`${missing.length?`<div class="discover-section-title"><div><strong>${missing.length} possíveis itens que não encontrei no XML</strong><span>Confira a fonte antes de adicionar.</span></div></div>${missing.map(resultCard).join('')}`:''}${existing.length?`<details class="discover-existing"><summary>${existing.length} resultados que parecem já estar no Lattes</summary><div>${existing.slice(0,20).map(resultCard).join('')}</div></details>`:''}`}
    const cost=q('#discoveryCost');if(cost)cost.textContent=D.lastMeta?.estimated_cost_usd!=null?`Busca ampla: ~US$ ${Number(D.lastMeta.estimated_cost_usd).toFixed(3)}`:'OpenAlex + Crossref: sem custo de IA';window.lucide?.createIcons?.();}

  function activate(){qa('.nav-item').forEach(x=>x.classList.remove('active'));qa('.view').forEach(x=>x.classList.remove('active'));q('[data-view="discovery"]')?.classList.add('active');q('#view-discovery')?.classList.add('active');const t=q('#pageTitle');if(t)t.textContent='Descobertas públicas.';render();scrollTo({top:0,behavior:'smooth'})}
  function install(){if(q('#view-discovery'))return;const nav=q('.nav-list');const anchor=q('[data-view="career"]');const b=document.createElement('button');b.className='nav-item';b.dataset.view='discovery';b.innerHTML='<i data-lucide="search-check"></i><span>Descobertas</span><span class="nav-badge neon" id="discoveryNavBadge">web</span>';nav?.insertBefore(b,anchor||null);b.addEventListener('click',activate);
    const main=q('.main');const career=q('#view-career');const section=document.createElement('section');section.className='view';section.id='view-discovery';section.innerHTML=`<div class="section-intro discover-intro"><div><div class="eyebrow">DESCOBERTAS PÚBLICAS</div><h2>O que você fez — e talvez nunca tenha colocado no Lattes.</h2><p>O Easy Lattes procura em fontes acadêmicas e, quando o backend estiver ligado, também em páginas públicas da web. Tudo vem com fonte e precisa da sua confirmação.</p></div><button class="btn neon" id="runDiscoveryBtn"><i data-lucide="radar"></i>Vasculhar fontes públicas</button></div><section class="discover-hero"><div><div class="mini-label neon-text">IDENTIDADE DA BUSCA</div><h3>Primeiro confirmamos quem é você.</h3><p>Isso reduz falsos positivos de pessoas com nomes parecidos.</p></div><div class="discover-fields"><label>Nome<input id="discoveryName" placeholder="Nome completo"></label><label>Instituição<input id="discoveryInstitution" placeholder="Universidade / instituição"></label></div><label class="discover-consent"><input type="checkbox" id="discoveryConsent"><span>Autorizo esta busca por informações acadêmicas e profissionais que já estejam publicamente acessíveis na internet. Nada será adicionado ao meu XML sem minha confirmação.</span></label></section><div class="discover-stats"><article><span>Possivelmente ausentes</span><strong id="discoveryMissingCount">0</strong></article><article><span>Resultados analisados</span><strong id="discoveryTotalCount">0</strong></article><article class="discover-cost-card"><span>Custo desta camada</span><strong id="discoveryCost">OpenAlex + Crossref: sem custo de IA</strong></article></div><section class="discover-source-strip"><div id="discoveryAuthorMatch"></div><div class="discover-source-badges"><span>OpenAlex</span><span>Crossref</span><span>Web pública*</span></div></section><div id="discoveryResults"></div><div class="discover-note"><i data-lucide="shield-check"></i><div><strong>Regra do produto</strong><p>Resultado de busca não é prova de autoria. O Easy Lattes mostra a fonte, cruza com nome/afiliação e deixa o professor decidir. Páginas privadas, áreas logadas e dados não públicos ficam fora da busca.</p></div></div>`;main?.insertBefore(section,career||null);
    q('#runDiscoveryBtn')?.addEventListener('click',runSearch);document.addEventListener('click',e=>{const a=e.target.closest('[data-discover-review]');if(a)reviewDiscovery(a.dataset.discoverReview);const i=e.target.closest('[data-discover-ignore]');if(i)ignoreDiscovery(i.dataset.discoverIgnore);const o=e.target.closest('[data-discover-open]');if(o)openDiscovery(o.dataset.discoverOpen)});window.addEventListener('easy-lattes:xml-ready',()=>setTimeout(render,50));render();window.lucide?.createIcons?.();}

  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();