(() => {
  const q=(s,r=document)=>r.querySelector(s), qa=(s,r=document)=>[...r.querySelectorAll(s)];
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const V8=new Set(['artigo','evento_completo','evento_resumo_expandido','evento_resumo','software','produto_tecnologico','material_didatico','relatorio_pesquisa']);
  function toast(msg){const s=q('#toastStack');if(!s)return;const d=document.createElement('div');d.className='toast';d.textContent=msg;s.appendChild(d);setTimeout(()=>d.remove(),3300)}
  const val=id=>q(`#${id}`)?.value?.trim()||'';
  function node(doc,name,attrs={}){const el=doc.createElement(name);for(const[k,v]of Object.entries(attrs))if(v!==''&&v!=null)el.setAttribute(k,String(v));return el}
  function direct(p,name){return p?[...p.children].find(x=>x.tagName===name)||null:null}
  function ordered(doc,p,name,order){let el=direct(p,name);if(el)return el;el=doc.createElement(name);const idx=order.indexOf(name),before=[...p.children].find(c=>{const i=order.indexOf(c.tagName);return i>=0&&i>idx});p.insertBefore(el,before||null);return el}
  function seq(doc){const nums=qa('[SEQUENCIA-PRODUCAO]',doc).map(x=>+x.getAttribute('SEQUENCIA-PRODUCAO')).filter(Number.isFinite);return String((nums.length?Math.max(...nums):0)+1)}
  function root(doc){return doc.querySelector('CURRICULO-VITAE')||doc.documentElement}
  function bib(doc){return ordered(doc,root(doc),'PRODUCAO-BIBLIOGRAFICA',['DADOS-GERAIS','PRODUCAO-BIBLIOGRAFICA','PRODUCAO-TECNICA','OUTRA-PRODUCAO','DADOS-COMPLEMENTARES'])}
  function tech(doc){return ordered(doc,root(doc),'PRODUCAO-TECNICA',['DADOS-GERAIS','PRODUCAO-BIBLIOGRAFICA','PRODUCAO-TECNICA','OUTRA-PRODUCAO','DADOS-COMPLEMENTARES'])}
  function demaisTech(doc){return ordered(doc,tech(doc),'DEMAIS-TIPOS-DE-PRODUCAO-TECNICA',['CULTIVAR-REGISTRADA','SOFTWARE','PATENTE','CULTIVAR-PROTEGIDA','DESENHO-INDUSTRIAL','MARCA','TOPOGRAFIA-DE-CIRCUITO-INTEGRADO','PRODUTO-TECNOLOGICO','PROCESSOS-OU-TECNICAS','TRABALHO-TECNICO','DEMAIS-TIPOS-DE-PRODUCAO-TECNICA'])}
  function authorNode(doc,name,order=1){return node(doc,'AUTORES',{'NOME-COMPLETO-DO-AUTOR':name,'NOME-PARA-CITACAO':name,'ORDEM-DE-AUTORIA':order})}
  function currentName(doc){return doc.querySelector('DADOS-GERAIS')?.getAttribute('NOME-COMPLETO')||''}
  function addAuthors(doc,wrap){let authors=[];try{authors=JSON.parse(q('#intakeModal')?.dataset?.v8Authors||'[]')}catch(_){}if(!authors.length){const me=currentName(doc);if(me)authors=[me]}[...new Set(authors.filter(Boolean))].slice(0,80).forEach((a,i)=>wrap.appendChild(authorNode(doc,a,i+1)))}
  function data(){return{type:val('intakeType'),year:val('intakeYear'),title:val('intakeTitle'),institution:val('intakeInstitution'),event:val('intakeEvent'),role:val('intakeRole'),hours:val('intakeHours'),person:val('intakePerson'),local:val('intakeLocal'),city:val('intakeCity'),notes:val('intakeNotes'),doi:val('intakeDoi').replace(/^https?:\/\/(dx\.)?doi\.org\//i,''),journal:val('intakeJournal'),subtype:val('intakeSubtype')}}
  function addArticle(doc,d){const group=ordered(doc,bib(doc),'ARTIGOS-PUBLICADOS',['TRABALHOS-EM-EVENTOS','ARTIGOS-PUBLICADOS','ARTIGOS-ACEITOS-PARA-PUBLICACAO','LIVROS-E-CAPITULOS','TEXTOS-EM-JORNAIS-OU-REVISTAS','DEMAIS-TIPOS-DE-PRODUCAO-BIBLIOGRAFICA']);const w=node(doc,'ARTIGO-PUBLICADO',{'SEQUENCIA-PRODUCAO':seq(doc)});w.appendChild(node(doc,'DADOS-BASICOS-DO-ARTIGO',{NATUREZA:'COMPLETO','TITULO-DO-ARTIGO':d.title,'ANO-DO-ARTIGO':d.year,'PAIS-DE-PUBLICACAO':'Brasil',IDIOMA:'Português','MEIO-DE-DIVULGACAO':'MEIO_DIGITAL','FLAG-RELEVANCIA':'NAO',DOI:d.doi,'FLAG-DIVULGACAO-CIENTIFICA':'SIM'}));w.appendChild(node(doc,'DETALHAMENTO-DO-ARTIGO',{'TITULO-DO-PERIODICO-OU-REVISTA':d.journal||d.event}));addAuthors(doc,w);group.appendChild(w)}
  function addEventWork(doc,d,nature){const group=ordered(doc,bib(doc),'TRABALHOS-EM-EVENTOS',['TRABALHOS-EM-EVENTOS','ARTIGOS-PUBLICADOS','ARTIGOS-ACEITOS-PARA-PUBLICACAO','LIVROS-E-CAPITULOS','TEXTOS-EM-JORNAIS-OU-REVISTAS','DEMAIS-TIPOS-DE-PRODUCAO-BIBLIOGRAFICA']);const w=node(doc,'TRABALHO-EM-EVENTOS',{'SEQUENCIA-PRODUCAO':seq(doc)});w.appendChild(node(doc,'DADOS-BASICOS-DO-TRABALHO',{NATUREZA:nature,'TITULO-DO-TRABALHO':d.title,'ANO-DO-TRABALHO':d.year,'PAIS-DO-EVENTO':'Brasil',IDIOMA:'Português','MEIO-DE-DIVULGACAO':'MEIO_DIGITAL','FLAG-RELEVANCIA':'NAO',DOI:d.doi,'FLAG-DIVULGACAO-CIENTIFICA':'SIM'}));w.appendChild(node(doc,'DETALHAMENTO-DO-TRABALHO',{'NOME-DO-EVENTO':d.event,'ANO-DE-REALIZACAO':d.year,'CIDADE-DO-EVENTO':d.city,'TITULO-DOS-ANAIS-OU-PROCEEDINGS':d.journal}));addAuthors(doc,w);group.appendChild(w)}
  function insertTechDirect(doc,w,tag){const g=tech(doc),order=['CULTIVAR-REGISTRADA','SOFTWARE','PATENTE','CULTIVAR-PROTEGIDA','DESENHO-INDUSTRIAL','MARCA','TOPOGRAFIA-DE-CIRCUITO-INTEGRADO','PRODUTO-TECNOLOGICO','PROCESSOS-OU-TECNICAS','TRABALHO-TECNICO','DEMAIS-TIPOS-DE-PRODUCAO-TECNICA'];const idx=order.indexOf(tag),before=[...g.children].find(c=>{const i=order.indexOf(c.tagName);return i>=0&&i>idx});g.insertBefore(w,before||null)}
  function addSoftware(doc,d){const w=node(doc,'SOFTWARE',{'SEQUENCIA-PRODUCAO':seq(doc)});w.appendChild(node(doc,'DADOS-BASICOS-DO-SOFTWARE',{NATUREZA:/multim/i.test(d.subtype)?'MULTIMIDIA':'COMPUTACIONAL','TITULO-DO-SOFTWARE':d.title,ANO:d.year,PAIS:'Brasil',IDIOMA:'Português','MEIO-DE-DIVULGACAO':'WEB','FLAG-RELEVANCIA':'NAO','FLAG-DIVULGACAO-CIENTIFICA':'SIM','FLAG-POTENCIAL-INOVACAO':'NAO'}));w.appendChild(node(doc,'DETALHAMENTO-DO-SOFTWARE',{FINALIDADE:d.notes,PLATAFORMA:d.role,DISPONIBILIDADE:'NAO_INFORMADO','INSTITUICAO-FINANCIADORA':d.institution}));addAuthors(doc,w);insertTechDirect(doc,w,'SOFTWARE')}
  function addProduct(doc,d){const w=node(doc,'PRODUTO-TECNOLOGICO',{'SEQUENCIA-PRODUCAO':seq(doc)});w.appendChild(node(doc,'DADOS-BASICOS-DO-PRODUTO-TECNOLOGICO',{'TIPO-PRODUTO':/piloto/i.test(d.subtype)?'PILOTO':/protot/i.test(d.subtype)?'PROTOTIPO':/projeto/i.test(d.subtype)?'PROJETO':'OUTRO',NATUREZA:d.role||'OUTRA','TITULO-DO-PRODUTO':d.title,ANO:d.year,PAIS:'Brasil','MEIO-DE-DIVULGACAO':'WEB','FLAG-RELEVANCIA':'NAO'}));w.appendChild(node(doc,'DETALHAMENTO-DO-PRODUTO-TECNOLOGICO',{FINALIDADE:d.notes,CIDADE:d.city,'INSTITUICAO-FINANCIADORA':d.institution}));addAuthors(doc,w);insertTechDirect(doc,w,'PRODUTO-TECNOLOGICO')}
  function addMaterial(doc,d){const w=node(doc,'DESENVOLVIMENTO-DE-MATERIAL-DIDATICO-OU-INSTRUCIONAL',{'SEQUENCIA-PRODUCAO':seq(doc)});w.appendChild(node(doc,'DADOS-BASICOS-DO-MATERIAL-DIDATICO-OU-INSTRUCIONAL',{NATUREZA:d.subtype||d.role||'Material didático','TITULO':d.title,ANO:d.year,PAIS:'Brasil',IDIOMA:'Português','MEIO-DE-DIVULGACAO':'MEIO_DIGITAL','FLAG-RELEVANCIA':'NAO','FLAG-DIVULGACAO-CIENTIFICA':'SIM'}));w.appendChild(node(doc,'DETALHAMENTO-DO-MATERIAL-DIDATICO-OU-INSTRUCIONAL',{FINALIDADE:d.notes}));addAuthors(doc,w);demaisTech(doc).appendChild(w)}
  function addReport(doc,d){const w=node(doc,'RELATORIO-DE-PESQUISA',{'SEQUENCIA-PRODUCAO':seq(doc)});w.appendChild(node(doc,'DADOS-BASICOS-DO-RELATORIO-DE-PESQUISA',{TITULO:d.title,ANO:d.year,PAIS:'Brasil',IDIOMA:'Português','MEIO-DE-DIVULGACAO':'MEIO_DIGITAL','FLAG-RELEVANCIA':'NAO'}));w.appendChild(node(doc,'DETALHAMENTO-DO-RELATORIO-DE-PESQUISA',{'NOME-DO-PROJETO':d.event,DISPONIBILIDADE:'NAO_INFORMADO','INSTITUICAO-FINANCIADORA':d.institution}));addAuthors(doc,w);demaisTech(doc).appendChild(w)}
  function history(d){window.__easyLattesV8Changes=window.__easyLattesV8Changes||[];window.__easyLattesV8Changes.push({...d,at:new Date().toISOString()});const list=q('#changeList');if(list){if(list.querySelector('.empty-state'))list.innerHTML='';const a=document.createElement('article');a.className='change-item';a.innerHTML=`<div class="change-icon"><i data-lucide="plus"></i></div><div><strong>${esc(d.title)}</strong><p>${esc(label(d.type))} • adicionado pela Entrada Inteligente</p></div>`;list.prepend(a)}const n=window.__easyLattesV8Changes.length;if(q('#exportChangeCount'))q('#exportChangeCount').textContent=String(n);if(q('#navChangeBadge'))q('#navChangeBadge').textContent=String(n);if(q('#downloadXmlBtn'))q('#downloadXmlBtn').disabled=false;window.lucide?.createIcons?.()}
  function label(t){return({artigo:'Artigo publicado',evento_completo:'Trabalho completo em evento',evento_resumo_expandido:'Resumo expandido',evento_resumo:'Resumo em evento',software:'Software',produto_tecnologico:'Produto tecnológico',material_didatico:'Material didático/instrucional',relatorio_pesquisa:'Relatório de pesquisa'})[t]||t}
  function addV8(){const doc=window.__easyLattesCurrentDoc;if(!doc)return toast('Importe o XML antes de adicionar.');const d=data();if(!d.title)return toast('Confira o título antes de adicionar.');try{if(d.type==='artigo')addArticle(doc,d);else if(d.type==='evento_completo')addEventWork(doc,d,'COMPLETO');else if(d.type==='evento_resumo_expandido')addEventWork(doc,d,'RESUMO_EXPANDIDO');else if(d.type==='evento_resumo')addEventWork(doc,d,'RESUMO');else if(d.type==='software')addSoftware(doc,d);else if(d.type==='produto_tecnologico')addProduct(doc,d);else if(d.type==='material_didatico')addMaterial(doc,d);else if(d.type==='relatorio_pesquisa')addReport(doc,d);history(d);q('#intakeModal')?.classList.remove('open');setTimeout(()=>{if(q('#intakeModal'))q('#intakeModal').hidden=true},160);window.dispatchEvent(new CustomEvent('easy-lattes:xml-mutated',{detail:{type:d.type,title:d.title}}));toast(`${label(d.type)} adicionado à cópia do XML.`)}catch(e){console.error(e);toast('Não consegui inserir esse tipo no XML. O registro não foi aplicado.')}}
  function addOptions(){const s=q('#intakeType');if(!s||s.dataset.v8)return;s.dataset.v8='1';const opts=[['artigo','Artigo publicado'],['evento_completo','Trabalho completo em evento'],['evento_resumo_expandido','Resumo expandido em evento'],['evento_resumo','Resumo em evento'],['software','Software'],['produto_tecnologico','Produto tecnológico / produto intelectual'],['material_didatico','Material didático / instrucional'],['relatorio_pesquisa','Relatório de pesquisa']];opts.reverse().forEach(([v,t])=>{const o=document.createElement('option');o.value=v;o.textContent=t;s.insertBefore(o,s.firstChild)});s.addEventListener('change',renderExtras)}
  function renderExtras(){const form=q('.intake-form');if(!form)return;let box=q('#intakeExtrasV8');if(!box){box=document.createElement('div');box.id='intakeExtrasV8';box.className='intake-v8-extras';box.innerHTML=`<div class="intake-field"><label>DOI</label><input id="intakeDoi" placeholder="10.xxxx/..."></div><div class="intake-field"><label>Periódico / Anais</label><input id="intakeJournal" placeholder="Nome do periódico ou anais"></div><div class="intake-field wide"><label>Natureza / subtipo</label><input id="intakeSubtype" placeholder="Ex.: protótipo, computacional, material educativo..."></div><div class="intake-v8-meta wide" id="intakeV8Meta"></div>`;form.insertBefore(box,q('.intake-field.wide:last-child',form)||null)}const t=val('intakeType'),show=V8.has(t);box.hidden=!show;if(show){const isBib=/^artigo|^evento_/.test(t);q('#intakeDoi').closest('.intake-field').hidden=!isBib;q('#intakeJournal').closest('.intake-field').hidden=!isBib;q('#intakeSubtype').closest('.intake-field').hidden=/^artigo$|^evento_/.test(t)}}
  async function enrichDoi(doi){if(!doi)return;const meta=q('#intakeV8Meta');if(meta)meta.textContent='Buscando metadados do DOI…';try{const r=await fetch(`https://api.crossref.org/works/${encodeURIComponent(doi)}`);if(!r.ok)throw Error();const w=(await r.json()).message||{};if(!val('intakeTitle')&&(w.title||[])[0])q('#intakeTitle').value=(w.title||[])[0];if(!val('intakeYear'))q('#intakeYear').value=w.published?.['date-parts']?.[0]?.[0]||'';if(!val('intakeJournal'))q('#intakeJournal').value=(w['container-title']||[])[0]||'';const authors=(w.author||[]).map(a=>`${a.given||''} ${a.family||''}`.trim()).filter(Boolean);q('#intakeModal').dataset.v8Authors=JSON.stringify(authors);if(meta)meta.innerHTML=`<strong>Crossref confirmado:</strong> ${authors.length} autor(es) encontrados${(w['container-title']||[])[0]?` • ${esc((w['container-title']||[])[0])}`:''}.`;}catch{if(meta)meta.textContent='Não consegui enriquecer esse DOI agora; você ainda pode revisar manualmente.'}}
  function inferFromModal(){addOptions();renderExtras();const notes=val('intakeNotes'),doi=(notes.match(/doi\.org\/([^\s]+)/i)||notes.match(/\b(10\.\d{4,9}\/[^\s]+)/i)||[])[1]||'';const isCrossref=/Crossref/i.test(notes)||!!doi;if(isCrossref){q('#intakeType').value='artigo';renderExtras();if(doi)q('#intakeDoi').value=doi.replace(/[),.;]+$/,'');const lines=notes.split(/\n+/).map(x=>x.trim()).filter(Boolean);const journal=lines.find(x=>!/Fonte pública|doi\.org|^https?:/i.test(x));if(journal&&!val('intakeJournal'))q('#intakeJournal').value=journal;if(doi)enrichDoi(q('#intakeDoi').value)}}
  function installStyles(){if(document.querySelector('style[data-intake-v8]'))return;const st=document.createElement('style');st.dataset.intakeV8='1';st.textContent='.intake-v8-extras{display:contents}.intake-v8-meta{font-size:11px;line-height:1.45;color:#667085;padding:0 4px}.intake-v8-meta strong{color:#101828}';document.head.appendChild(st)}
  function init(){installStyles();addOptions();const modal=q('#intakeModal');if(modal){new MutationObserver(()=>{if(!modal.hidden||modal.classList.contains('open'))setTimeout(inferFromModal,30)}).observe(modal,{attributes:true,attributeFilter:['hidden','class']})}document.addEventListener('click',e=>{const b=e.target.closest('#intakeConfirm');if(!b)return;const t=val('intakeType');if(!V8.has(t))return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();addV8()},true)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,220));else setTimeout(init,220);
})();