(() => {
  const VERSION = '20260917-1145';
  const REGION = 'southamerica-east1';
  const q = (s, r = document) => r.querySelector(s);
  const qa = (s, r = document) => [...r.querySelectorAll(s)];
  const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const P = {source:'',declaration:'',doctype:'',encoding:'UTF-8',originalId:'',lastValidation:null,backend:{configured:false,online:false,projectId:'',health:null,error:''}};
  function toast(message){const stack=q('#toastStack');if(!stack)return;const d=document.createElement('div');d.className='toast';d.textContent=message;stack.appendChild(d);setTimeout(()=>d.remove(),3600)}
  function clientId(){let id=localStorage.getItem('easyLattesClientId');if(!id){id=crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`;localStorage.setItem('easyLattesClientId',id)}return id}
  function validProjectId(value){return /^[a-z][a-z0-9-]{4,40}$/i.test(String(value||'').trim())}
  function applyProjectId(projectId){const id=String(projectId||'').trim();if(!validProjectId(id))return false;const base=`https://${REGION}-${id}.cloudfunctions.net`;window.EASY_LATTES_CONFIG={...(window.EASY_LATTES_CONFIG||{}),firebaseProjectId:id,aiEndpoint:`${base}/careerAnalysis`,webDiscoveryEndpoint:`${base}/webDiscovery`,healthEndpoint:`${base}/health`};window.EASY_LATTES_AI_ENDPOINT=window.EASY_LATTES_CONFIG.aiEndpoint;window.EASY_LATTES_WEB_DISCOVERY_ENDPOINT=window.EASY_LATTES_CONFIG.webDiscoveryEndpoint;P.backend.configured=true;P.backend.projectId=id;localStorage.setItem('easyLattesFirebaseProjectId',id);return true}
  function restoreConfig(){const id=localStorage.getItem('easyLattesFirebaseProjectId')||'';if(id)applyProjectId(id)}
  const nativeFetch=window.fetch.bind(window);window.fetch=function(input,init={}){try{const url=typeof input==='string'?input:input?.url||'';const endpoints=[window.EASY_LATTES_AI_ENDPOINT,window.EASY_LATTES_WEB_DISCOVERY_ENDPOINT,window.EASY_LATTES_CONFIG?.healthEndpoint].filter(Boolean);if(endpoints.some(x=>url.startsWith(x))){const headers=new Headers(init.headers||(typeof input!=='string'?input?.headers:undefined)||{});headers.set('X-Easy-Lattes-Client',clientId());init={...init,headers}}}catch(_){}return nativeFetch(input,init)};
  function captureXml(source,doc){P.source=String(source||'');P.declaration=P.source.match(/^\s*(<\?xml[^?]*\?>)/i)?.[1]||'';P.doctype=P.source.match(/<!DOCTYPE\s+CURRICULO-VITAE[^>]*>/i)?.[0]||'';P.encoding=P.declaration.match(/encoding\s*=\s*["']([^"']+)["']/i)?.[1]?.toUpperCase()||'UTF-8';const root=doc?.querySelector?.('CURRICULO-VITAE')||doc?.documentElement;P.originalId=root?.getAttribute?.('NUMERO-IDENTIFICADOR')||'';setTimeout(renderXmlValidation,100)}
  function currentDoc(){return window.__easyLattesCurrentDoc||null}
  function serializeXml(){const doc=currentDoc();if(!doc)throw new Error('Nenhum XML carregado');let body=new XMLSerializer().serializeToString(doc);body=body.replace(/^\s*<\?xml[^?]*\?>\s*/i,'');if(P.doctype)body=body.replace(/<!DOCTYPE\s+CURRICULO-VITAE[^>]*>\s*/i,'');const encoding=/8859-1|ISO-8859-1|LATIN-1/i.test(P.encoding)?'ISO-8859-1':'UTF-8';const declaration=`<?xml version="1.0" encoding="${encoding}"?>`;const parts=[declaration];if(P.doctype)parts.push(P.doctype);parts.push(body);return{text:parts.join('\n'),encoding}}
  function validateXml(){const doc=currentDoc();if(!doc)return{ok:false,errors:['Nenhum XML carregado.'],warnings:[],encoding:''};const errors=[],warnings=[];let serialized;try{serialized=serializeXml()}catch(e){return{ok:false,errors:[e.message],warnings:[],encoding:''}}const reparsed=new DOMParser().parseFromString(serialized.text,'application/xml');if(reparsed.querySelector('parsererror'))errors.push('O XML gerado não passou na validação sintática do navegador.');const root=reparsed.querySelector('CURRICULO-VITAE')||reparsed.documentElement;if(root?.tagName!=='CURRICULO-VITAE')errors.push('Elemento raiz CURRICULO-VITAE não encontrado.');const id=root?.getAttribute?.('NUMERO-IDENTIFICADOR')||'';if(P.originalId&&id!==P.originalId)errors.push('O identificador original do currículo foi alterado.');if(!P.doctype)warnings.push('O XML original não continha um DOCTYPE detectável; o Easy Lattes não inventou um.');if(!P.declaration)warnings.push('A declaração XML original não foi encontrada; a saída usará UTF-8.');const emptyTitles=qa('[SEQUENCIA-PRODUCAO]',reparsed).filter(el=>{const own=[el,...qa('*',el)];return !own.some(x=>[...(x.attributes||[])].some(a=>/^(TITULO|TITULO-|NOME-DO-PROJETO|NOME-DO-EVENTO)/i.test(a.name)&&String(a.value||'').trim()))}).length;if(emptyTitles)warnings.push(`${emptyTitles} registro(s) de produção não têm título/nome detectável. Isso pode já existir no XML original.`);const result={ok:errors.length===0,errors,warnings,encoding:serialized.encoding,doctype:!!P.doctype,bytes:serialized.text.length};P.lastValidation=result;return result}
  function encodeLatin1Xml(text){let safe='';for(const ch of text){const cp=ch.codePointAt(0);safe+=cp<=255?ch:`&#${cp};`}const bytes=new Uint8Array(safe.length);for(let i=0;i<safe.length;i++)bytes[i]=safe.charCodeAt(i)&0xff;return bytes}
  function downloadBlob(blob,filename){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1200)}
  function robustDownload(){const validation=validateXml();renderXmlValidation();if(!validation.ok){toast('O XML não foi baixado: há um erro estrutural que precisa ser corrigido.');return}const{text,encoding}=serializeXml();const data=encoding==='ISO-8859-1'?encodeLatin1Xml(text):new TextEncoder().encode(text);const blob=new Blob([data],{type:`application/xml;charset=${encoding.toLowerCase()}`});downloadBlob(blob,`easy-lattes-corrigido-${new Date().toISOString().slice(0,10)}.xml`);toast(`XML gerado preservando ${encoding}${P.doctype?' e o DOCTYPE original':''}.`)}
  function downloadOriginal(){if(!P.source)return toast('Importe seu XML original primeiro.');const enc=/8859-1|ISO-8859-1|LATIN-1/i.test(P.encoding)?'ISO-8859-1':'UTF-8';const data=enc==='ISO-8859-1'?encodeLatin1Xml(P.source):new TextEncoder().encode(P.source);downloadBlob(new Blob([data],{type:`application/xml;charset=${enc.toLowerCase()}`}), 'easy-lattes-backup-original.xml')}
  function validationHtml(v){if(!currentDoc())return `<div class="xml-health empty"><div class="xml-health-icon"><i data-lucide="shield"></i></div><div><strong>Importe um XML para validar a saída.</strong><p>O Easy Lattes preserva o original e só trabalha sobre uma cópia.</p></div></div>`;const cls=v.ok?'ok':'bad',title=v.ok?'Estrutura XML íntegra':'O XML precisa de atenção';const details=[`<span><i data-lucide="${v.ok?'check':'x'}"></i>Sintaxe ${v.ok?'válida':'com erro'}</span>`,`<span><i data-lucide="file-code-2"></i>${esc(v.encoding||'—')}</span>`,`<span><i data-lucide="${v.doctype?'check':'info'}"></i>${v.doctype?'DOCTYPE original preservado':'DOCTYPE não detectado'}</span>`].join('');return `<div class="xml-health ${cls}"><div class="xml-health-icon"><i data-lucide="${v.ok?'shield-check':'shield-alert'}"></i></div><div class="xml-health-main"><strong>${title}</strong><p>${v.ok?'A cópia consegue ser serializada e reaberta sem erro estrutural. A confirmação final acontece na importação da Plataforma Lattes.':'Corrija os erros antes de baixar.'}</p><div class="xml-health-meta">${details}</div>${v.errors?.length?`<div class="xml-health-errors">${v.errors.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`:''}${v.warnings?.length?`<details><summary>${v.warnings.length} aviso(s)</summary><div>${v.warnings.map(x=>`<p>${esc(x)}</p>`).join('')}</div></details>`:''}</div></div>`}
  function renderXmlValidation(){const target=q('#xmlValidationV6');if(!target)return;target.innerHTML=validationHtml(validateXml());window.lucide?.createIcons?.()}
  function installReportGuard(){const report=q('#view-report');if(!report||q('#xmlValidationV6'))return;const disclaimer=q('.disclaimer-box',report),section=document.createElement('section');section.className='panel full xml-validation-panel';section.innerHTML=`<div class="panel-head"><div><div class="panel-kicker">SEGURANÇA DO ARQUIVO</div><h3>Validação antes de baixar</h3></div><button class="btn ghost" id="downloadOriginalXmlV6"><i data-lucide="archive"></i>Backup do original</button></div><div id="xmlValidationV6"></div>`;report.insertBefore(section,disclaimer||null);q('#downloadOriginalXmlV6')?.addEventListener('click',downloadOriginal);const btn=q('#downloadXmlBtn');btn?.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();robustDownload()},true);renderXmlValidation()}
  async function testBackend(){const endpoint=window.EASY_LATTES_CONFIG?.healthEndpoint;P.backend.online=false;P.backend.error='';if(!endpoint){renderSystem();return false}try{const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),7000);const r=await fetch(endpoint,{signal:ctrl.signal});clearTimeout(timer);if(!r.ok)throw new Error(`HTTP ${r.status}`);P.backend.health=await r.json();P.backend.online=!!P.backend.health?.ok}catch(e){P.backend.error=e?.name==='AbortError'?'tempo esgotado':String(e?.message||e)}renderSystem();return P.backend.online}
  function systemCard(icon,title,value,text,cls=''){return `<article class="system-card ${cls}"><div class="system-icon"><i data-lucide="${icon}"></i></div><div><span>${esc(title)}</span><strong>${esc(value)}</strong><p>${esc(text)}</p></div></article>`}
  function renderSystem(){const box=q('#systemContentV6');if(!box)return;const xml=!!currentDoc(),backend=P.backend.online;box.innerHTML=`<div class="system-v6-hero"><div><div class="system-kicker">EASY LATTES • DIAGNÓSTICO</div><h2>${backend?'Tudo pronto para IA.':'O núcleo já funciona. Falta uma ativação única para a IA.'}</h2><p>${backend?'Análise generativa e descoberta ampla estão conectadas ao backend protegido.':'Você pode usar XML, auditoria, Caixa Acadêmica, Crossref e a análise local agora. A IA generativa e a busca ampla exigem um backend protegido uma única vez.'}</p></div><div class="system-big-status ${backend?'on':'partial'}"><i data-lucide="${backend?'badge-check':'plug-zap'}"></i><strong>${backend?'ONLINE':'LOCAL ATIVO'}</strong></div></div><div class="system-grid">${systemCard('laptop','Processamento local','ATIVO','Leitura do XML, auditoria, comprovantes e análise local rodam no navegador.','on')}${systemCard('file-code-2','XML carregado',xml?'SIM':'AINDA NÃO',xml?'A cópia está disponível para revisão e validação.':'Importe seu XML quando quiser testar seu currículo.',xml?'on':'')}${systemCard('brain-circuit','IA generativa',backend?'CONECTADA':'PENDENTE',backend?'A chave fica protegida no servidor.':'Precisa de uma função Firebase com uma chave de API protegida.',backend?'on':'')}${systemCard('search-check','Busca ampla na web',backend?'CONECTADA':'PENDENTE',backend?'Usa pesquisa web com controle de custo e cache.':'OpenAlex/Crossref podem funcionar antes; a busca ampla depende do backend.',backend?'on':'')}</div><section class="system-setup"><div><div class="mini-label neon-text">ATIVAÇÃO ÚNICA</div><h3>Depois disso, é só usar.</h3><p>Se a função Firebase já foi implantada, informe apenas o <strong>ID do projeto Firebase</strong>. O Easy Lattes monta sozinho os três endereços do backend.</p></div><div class="system-project-row"><input id="firebaseProjectIdV6" placeholder="ex.: meu-projeto-firebase" value="${esc(P.backend.projectId)}"><button class="btn neon" id="saveProjectV6"><i data-lucide="plug"></i>Salvar e testar</button></div><div class="system-help"><span><i data-lucide="key-round"></i>A chave da OpenAI nunca entra nesta página.</span><span><i data-lucide="wallet-cards"></i>Resultados repetidos podem vir do cache sem nova chamada paga.</span><span><i data-lucide="shield-check"></i>O XML bruto não é enviado para a análise de carreira.</span></div>${P.backend.error?`<div class="system-error">Backend ainda não respondeu: ${esc(P.backend.error)}</div>`:''}</section>`;q('#saveProjectV6')?.addEventListener('click',async()=>{const id=q('#firebaseProjectIdV6')?.value?.trim();if(!applyProjectId(id))return toast('Esse ID de projeto Firebase não parece válido.');renderSystem();const ok=await testBackend();toast(ok?'Backend conectado. IA e busca ampla estão prontas.':'Projeto salvo, mas o backend ainda não respondeu.')});window.lucide?.createIcons?.()}
  function activateSystem(){qa('.nav-item').forEach(x=>x.classList.remove('active'));qa('.view').forEach(x=>x.classList.remove('active'));q('[data-view="system-v6"]')?.classList.add('active');q('#view-system-v6')?.classList.add('active');const t=q('#pageTitle');if(t)t.textContent='Sistema e IA.';renderSystem();scrollTo({top:0,behavior:'smooth'})}
  function installSystem(){if(q('#view-system-v6'))return;const nav=q('.nav-list');if(nav){const b=document.createElement('button');b.className='nav-item system-nav-v6';b.dataset.view='system-v6';b.innerHTML='<i data-lucide="cpu"></i><span>Sistema</span><span class="nav-badge neon" id="systemBadgeV6">●</span>';nav.appendChild(b);b.addEventListener('click',activateSystem)}const main=q('.main'),section=document.createElement('section');section.className='view';section.id='view-system-v6';section.innerHTML=`<div class="section-intro"><div><div class="eyebrow">SISTEMA</div><h2>O que já funciona — e o que falta ativar uma vez.</h2><p>Sem terminal, sem adivinhação. O próprio Easy Lattes mostra o estado do produto.</p></div></div><div id="systemContentV6"></div>`;main?.appendChild(section);renderSystem()}
  function init(){restoreConfig();clientId();installReportGuard();installSystem();window.addEventListener('easy-lattes:xml-ready',e=>captureXml(e.detail?.source,e.detail?.doc));if(window.__easyLattesCurrentXmlText&&window.__easyLattesCurrentDoc)captureXml(window.__easyLattesCurrentXmlText,window.__easyLattesCurrentDoc);if(P.backend.configured)testBackend();window.lucide?.createIcons?.()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,180));else setTimeout(init,180);
})();